### ISSUE TITLE
Comments [$120]

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#10]
Similar to the files app it should be possible for users to comment on each card. 

- [ ] Check if it is possible to use the server comments app

**Comment by joergmschulz** [comment]
I'm not sure how this could be done without cluttering the user interface. I like the simplicity of the current concept (well, dragging the cards would be a plus, you already opened an issue for this one) IMHO it is enough to have the description for the cards.

**Comment by juliushaertl** [comment]
@joergmschulz I would prefer to keep the markdown description as a default and just use tabs for other stuff like the comments, just like it is handled in the files app.

![2017-02-01-193228_511x404_scrot](https://cloud.githubusercontent.com/assets/3404133/22520596/3ceab3f8-e8b5-11e6-80ee-eae98a28fdd3.png)

**Comment by jancborchardt** [comment]
Yup, very important for collaboration too. cc @blizzz for comments.

**Comment by blizzz** [comment]
Yes, it's possible to use comments in other apps. One example that does it is the [announcement center app](https://github.com/nextcloud/announcementcenter), related PRs: https://github.com/nextcloud/announcementcenter/pulls?q=is%3Apr+comment+is%3Aclosed

**Comment by juliushaertl** [comment]
Thanks for the hint.

**Comment by Nebri** [comment]
This seems pretty straight forward. @juliushaertl I'd be willing to give this a go. After reading this over it sounds like the majority wishes to see the comments as a tab under the details view that comes up on the right panel after clicking a card?

View screenshot below for how that comments tab would appear. Once you give me the go ahead I'll happily create a new branch for this issue and get to work. Been a long time since I last got to do any angularjs work!

![image](https://user-images.githubusercontent.com/3360697/42609181-3c85cb5e-8559-11e8-949a-d1c0a1007518.png)

**Comment by jancborchardt** [comment]
> it sounds like the majority wishes to see the comments as a tab under the details view that comes up on the right panel after clicking a card?

Yes – just keep in mind that we also have a plan in the Files app to combine the chronological information (Activity, Comments, Versions) into one timeline. Not sure if anything else is chronological for now, but keep that in mind for the future @juliushaertl @Nebri :)

**Comment by juliushaertl** [comment]
Good point @jancborchardt We need to remind that for comments and activity #211

**Comment by JumpLink** [comment]
@Nebri Do you want to implement this feature? Did you need help?

**Comment by Nebri** [comment]
@JumpLink No thank you, this is currently being handled by @juliushaertl . When I started commenting on this issue I had missed the fact that he is currently assigned to this task.

**Comment by laurentiu2** [comment]
> this is currently being handled by @juliushaertl 
and from nov 17, 2017 since Julius assigned himself, nothing happened! Wouldn't be better if Ryan handles this? btw awesome work on REST API :)

**Comment by juliushaertl** [comment]
@laurentiu2 @JumpLink Comments and activity have actually gotten a high priority issue in the last month so I'm activly working on it right now. Expect a pull request soon. Both features will land in the next relase probably around end of september.

**Comment by JumpLink** [comment]
Nce to hear, good luck!

**Comment by Nebri** [comment]
@laurentiu2 I appreciate your kind words regarding my work on the REST api. I would like to also gently remind that juliushaertl has much more on his plate regarding deck. Typically Pull Requests are created when one of two things happen. We need feedback on the work in progress, or we believe the work is ready to be reviewed for a merge. Just because you haven't seen the pull request yet, doesn't mean there isn't a branch with the work being done yet. Patience my friends, together deck will continue to improve. :)
