### ISSUE TITLE
Attach due date to cards

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/deck#106]
what do you think about a "exp. date" field? card should be highlighted (icon or background) when the date is exceeded.

**Comment by artemanufrij** [comment]
@juliushaertl if you approve my suggestion - so i can implement it.

**Comment by juliushaertl** [comment]
I am currently implementing a basic attachment api that will allow any type of data being attached to cards. That way we can also add dates, e.g. a due date to the card. I should have something testable ready by the end of this week.

**Comment by juliushaertl** [comment]
I'll keep you updated on that, so you can do the due date implementation if you want. :wink:

**Comment by x9t9** [comment]
Is attachments really easier / more correct way to go than simply add another field ? I think that due date is an inherited property of a task which is part of it's definition , and as such it should be handled , as opposed to attachments that can be seen more of a way to extend the "optional" properties or annexed Info related to the nature of the task .

**Comment by pixelipo** [comment]
but adding the date field to a single card should also mean creating a calendar (.ics) for the parent board, right?

**Comment by juliushaertl** [comment]
> Is attachments really easier / more correct way to go than simply add another field ?

I thought about that and it makes sense to me, also in terms of sorting/filtering from the database.
@artemanufrij Are you still open for implementing this one?

> but adding the date field to a single card should also mean creating a calendar (.ics) for the parent board, right? Something that can be handed over to the CalDAV and Calendar app.

Different issue, but yes, this is how this should be in the future.

**Comment by artemanufrij** [comment]
@juliushaertl yes...sure! I'm waiting for your "big release" ;)

**Comment by bjornnorman** [comment]
Linking cards with the tasks in SabreDav would enable using existing functionality for this and all the other features of the Nextcloud tasks - perhaps most easily done by just "including" the related task settings from the task app in the card properties when card is linked to a task. Further integration with tasks could include connecting tables with task lists (i.e. the CalDAV calendars), making the relations and coherent across the ... "board". :) CalDav also supports adding unlimited custom fields specific to Nextcloud so that special features unique to NC can be promoted without breaking compatibility with other clients.

**Comment by juliushaertl** [comment]
Sure, linking cards to existing tasks/events makes sense, but i think there are some issues:
- Permissions of CalDAV calendars differ from the boards permissions
- What due date will be shown when multiple tasks are linked

I'd prefer to go for a dedicated duedate per card for now.

My initial thought was to expose each card as a separate task, into a "calendar" for each board. See #15 for the dav integration thoughts.
