### ISSUE TITLE
Add description from curl POST request doesn't work

### ISSUE THREAD

**Issue by a11exandru** [nextcloud/deck#1138]
I tried to add a new card via API with curl POST request <curl -u username:password  -X PUT -H "OCS-APIRequest:true" -H "Content-Type:application/json" "https://nextcloud.local/index.php/apps/deck/api/v1.0/
boards/9/stacks/27/cards/132?title=thisistitle&description=thisisthedescription&type=plain&order=999&duedate=null">  but the description remains empty even if I do add the description attribute.

**Comment by putt1ck** [comment]
Does the new card get added, just no description?

**Comment by a11exandru** [comment]
Yes, @putt1ck !

**Comment by putt1ck** [comment]
@juliushaertl is anyone leading on API stuff at the moment?

**Comment by juliushaertl** [comment]
Yes, the initial api implementation only allows to set the title, type and order (https://deck.readthedocs.io/en/latest/API/#cards) However it of course would make sense to also set the other details on creation. cc @desperateCoder since we discussed this as well for the android app.

@putt1ck I try to catch up on issues that come up, but my time for deck is unfortunately rather limited at the moment. Contributions are always very welcome.

**Comment by juliushaertl** [comment]
Some code hints if someone wants to look into implementing this:

https://github.com/nextcloud/deck/blob/master/lib/Controller/CardApiController.php#L76
https://github.com/nextcloud/deck/blob/master/lib/Service/CardService.php#L158-L192

**Comment by putt1ck** [comment]
@juliushaertl the hints should help @a11exandru fix his own bug report :)

**Comment by a11exandru** [comment]
Thanks @juliushaertl ! I will look into it.

**Comment by desperateCoder** [comment]
@a11exandru @juliushaertl  that'd be great, that's where i'm stuck right now. Thanks in advance!
