### ISSUE TITLE
ER: Reduce time to delete kanban

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/deck#124]
10 seconds is a long time to wait for deleting a kanban. Imagine you are closing out (deleting) multiple old ones. It's a bit frustrating.

**Comment by artemanufrij** [comment]
It would be cool to have a option to delete it instant

**Comment by x9t9** [comment]
I agree with @artemanufrij . From the UX point of view, it is much better adding another action link on the same Countdown popup that would simply say "Delete now" , or "Just do it" while continuing to count . Simply reducing the count as the PR states is helpful only in a quite extreme use case , and in all the others can be dangerous. Another option that is widely used is the confirmation popup instead of the count ( along the lines of " are you sure ? "

**Comment by juliushaertl** [comment]
Closing in favor of #85
