### ISSUE TITLE
Add support for circles app [$15]

### ISSUE THREAD

**Issue by Pisoko** [nextcloud/deck#126]
Deck is not compatible with circle-app.
It would be nice to share the decks with the circle-defined contacts.

Greets from germany
Pisoko

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=44949962)](https://www.bountysource.com/issues/44949962-deck-and-circle-nextcloud-12?utm_source=44949962&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by splitt3r** [comment]
The solution could also be used for the [Polls](https://github.com/nextcloud/polls/issues/204) app 👍.

**Comment by splitt3r** [comment]
Basic group sharing is working now in my app :). I´m willing to implement it here once i finished the first version of my app.

@juliushaertl i noticed that nc does existence checking here https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/Controller/ShareAPIController.php#L319-L491 and also checks if e.g group sharing is allowed. Perhaps we should add that too when implementing circle sharing?

**Comment by juliushaertl** [comment]
Yes it would make sense to also respect that setting. It might be already respected when fetching the list of users/groups since we use a server API for that, but it should of course also be checked when the actual sharing happens.

**Comment by splitt3r** [comment]
Yeah, you are right. With support for circles we need to use the displayname instead uf the id because the circles have a pretty cryptic one. After some research it works pretty well for me :) https://github.com/splitt3r/mindmaps/blob/feature/rework-js/lib/Db/Acl.php#L66-L87 & https://github.com/splitt3r/mindmaps/blob/feature/rework-js/lib/Controller/AclController.php#L104-L141

**Comment by juliushaertl** [comment]
Implemented with #923
