### ISSUE TITLE
Add diagramme gantt

### ISSUE THREAD

**Issue by michelwend** [nextcloud/deck#134]
Hello
Is it possible to have an output in the form of a Gantt chart
Thank you

**Comment by x9t9** [comment]
until such time where a due date will be implemented ( maybe #106 ) , a gantt chart would make little sense ..

**Comment by juliushaertl** [comment]
@michelwend Thanks for the idea. Although i need to think about if it makes sense to include this into deck or if it would be better to solve something like this in a different app. 

@x9t9 Let's keep it open and move it to backlog for now.

**Comment by poVoq** [comment]
There has been a recent update to the really nice twproject gantt chart system, see:
https://roberto.open-lab.com/2017/04/05/new-gantt-editor-release-the-best-ever/
https://github.com/robicch/jQueryGantt
would be probably the best solution to add this.

**Comment by juliushaertl** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by aliceinwire** [comment]
Would be useful also here for better planning in advance.

**Comment by paulkernstock** [comment]
I would also like to see this happen.

**Comment by juliushaertl** [comment]
FIY @jeobz has been working on some basic gantt chart that uses the deck API. We were discussing about having a separate Nextcloud app for this as a PoC https://github.com/jeobz/NxDeckGantt

**Comment by aliceinwire** [comment]
would be nice to have NxDeck for better organization

**Comment by Shahin-rmz** [comment]
Hello,
any updates about this feature?

**Comment by Shahin-rmz** [comment]
> [NxDeckGantt](https://github.com/jeobz/NxDeckGantt) is apparently dead project. It has not been updated for thirteen months.
I have seen that the developer likes to maintain it, but he lacks time.
Also I don't know how can I help maintaining the project.
It's sad that Gantt chart is not integrate/ maintained in the Decks.

**Comment by Thomas131** [comment]
Probably adding an optional duration-field to the cards and using it in the calender-integration would be a good start imo.

As much as I want the feature, I don't think I have time for implementing it :(

Best regards,
Thomad

**Comment by Shahin-rmz** [comment]
There is a standard library for that in JS.
unfortunately I have absolutely no idea about JS.

**Comment by FesTGig** [comment]
Any hope to get the gantt view?
I think think that would be one of few features wich lead the decks app really in to productivity

**Comment by kirillvb** [comment]
I really hope this feature is added. For now, we are forced to transfer some of the work from a nextcloud to a separate server.

**Comment by ventolinmx** [comment]
I would also like to have Gantt in Nextcloud.

**Comment by gpsloco** [comment]
I get this feature request from the users of my instances pretty often. Even a basic implementation would be very helpful!

**Comment by derWalter** [comment]
dont know how this can be declined for so long ;(

**Comment by lapineige** [comment]
I'm interested too :)

As there is some interest for this feature, could the issue be reopened ?

**Comment by dualizeo** [comment]
Any other similar tools?

**Comment by dualizeo** [comment]
Any news on Gantt Charts for NextCloud ? or Sprints or Milestones Overview

**Comment by stefan-niedermann** [comment]
We heard you. There is obviously a use case for a Gantt view for Deck (and / or Tasks). You can find [the latest official statement above](https://github.com/nextcloud/deck/issues/134#issuecomment-448910458) stating, that this is **not on the roadmap of the Nextcloud GmbH**.

However, I'm going to lock this issue because of the <kbd>+1</kbd> spam that essentially adds no relevant information but makes it impossible to read and understand the issue. Please stop doing this in other issues and projects as well and learn about [**Github reactions**](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/).

Please feel free to start a new, separate app accessing the Deck data as suggested above or hire a paid developer if you are not a programmer. You can also use [Nextcloud Help](https://help.nextcloud.com/c/nextcloud-freelancing/looking/49) to coordinate efforts or gather some bucks for a freelancer. Given the amount of people involved in this issue, I am quite sure that there are some interested devs. In case the roadmap has changes, Nextcloud GmbH may unlock this issue.
