### ISSUE TITLE
Timeline and Activite

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/deck#1558]
**Describe the bug**
No change in the card description in the "Timeline" and in "Activite".
Sometimes it saves changes, but there are errors in "Activity".
Issues: #1557.

**To Reproduce**

1. Create a board.
2. Add stack.
3. Add card.
4. Add or change card description.
5. Go to Timeline.
6. Go to "Activity" Nextcloud.

**Expected behavior**
Save in the "Timeline" and "Activity" each change made to the card description.

**Screenshots**

![obraz](https://user-images.githubusercontent.com/47037905/75230453-ecb0e580-57b3-11ea-9efa-9ad71dfb516a.png)

![obraz](https://user-images.githubusercontent.com/47037905/75230688-6b0d8780-57b4-11ea-80b3-24bbf37d2a46.png)

![obraz](https://user-images.githubusercontent.com/47037905/75230780-91332780-57b4-11ea-8d42-ca16dbe5593d.png)

**Client details:**
   Win10
   Firefox
   73.0.1

**Nextcloud version:** (see Nextcloud admin page)
18.0.1

**Deck version:**
0.8.0

**Comment by Valdnet** [comment]
I noticed that the appearance of changes in "Timeline" and "Activite" appeared only after entering the "Deck" the next day.

In addition, the description of the change time in "Timeline" at the beginning was "in a few seconds" instead of "seconds ago".

**Comment by juliushaertl** [comment]
> Save in the "Timeline" and "Activity" each change made to the card description.
> I noticed that the appearance of changes in "Timeline" and "Activite" appeared only after entering the "Deck" the next day.

Yes, that is expected, we delay creating a activity entry for description changes until no changes were performed for 5 minutes or a different user edits the description. Otherwise there would be a massive amount of activity entries for every change that is saved due to auto save.

> In addition, the description of the change time in "Timeline" at the beginning was "in a few seconds" instead of "seconds ago".

This is most likely an issue with your local time and the server time not being in sync. The relative timestamp uses your computers time and compares it with the time stored in the activity that is coming from the server.
