### ISSUE TITLE
Rearange stacks

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#16]
It should be possible to change the order of the stacks by dragging them around.

**Comment by poVoq** [comment]
maybe there could be an option similar to the "archive unhide" button to lock and unload a board, which would also hide the "add new stack" part at the very right when locked.

**Comment by juliushaertl** [comment]
Good idea, so basically having a stack arange mode would help not having to much drag and drop handles around in daily use.

**Comment by xenithorb** [comment]
As it is right now, getting into this sort of methodology (im new to using this kind of thing) I didn't quite understand how to use it at first so my "stacks" were slightly out of order at first. I then thought that maybe I could move the stack around, but I couldn't. So a single out-of-place stack ruins the arrangement, and as far as I can tell it all has to be redone. 

Worse yet, if you accidentally delete a stack, the above applies because you can only add it back out of order. (as far as I can tell).
