### ISSUE TITLE
Wrap text properly around due date

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#1672]
- Wrap text around due date
- Make sure that editing is working multiline https://github.com/nextcloud/deck/issues/865
- Set a max-width for the due date

**Additional context**
![2020-06-23_15:31:12](https://user-images.githubusercontent.com/8270201/85409698-6ab8a980-b566-11ea-82f5-4cbe2fd3d579.png)
![2020-06-23_15:36:12](https://user-images.githubusercontent.com/8270201/85410219-1bbf4400-b567-11ea-8ec9-27d2fe1f257f.png)

**Comment by armaccloud** [comment]
Hi,

Extending on my previous remarks in #2081 I would like to chip in with some suggestions.

As you can see from this screenshot, the cards are beautifully formatted when there is no due date set. Especially in Dutch, you can see the due date has a long name, making the overall view look very untidy and difficult to navigate when there are many items (due to the lack of aesthetics, one tends to lose overview). This will partially be solved if the text wraps around the due date. However, this will still make the first line(s) look cramped as you can see in the screenshot.

![image](https://user-images.githubusercontent.com/9272078/87522950-8eaf6c80-c686-11ea-8354-14ba72264c7e.png)

What I noticed, is that there is not only the subject + due date on one line, but also the menu button.

- Would it be an option to move the menu button to the right-hand bottom?
- Is it an idea to decrease the height of the due date to its text size, so the subject text wraps around it for the second line?
- Another (my preferred) option would be to give the due date and subject their own line and decrease the height of the due date to its text size so it doesn't eat up so much space.

It would be nice to see a mock-up of the new view with the deck cards from my screenshot as an example, how would they look good in the new view? If it works for this use case, it would probably work well for other peoples decks as well.

**Comment by Hanskes** [comment]
Any progress??
