### ISSUE TITLE
Clone/copy a card

### ISSUE THREAD

**Issue by Nyco** [nextcloud/deck#1813]
**Is your feature request related to a problem? Please describe.**

When a user wants to:

* split a card
* copy the same card in another stack or board (for optional later editing)

the only option is to manually:

* go to the card
* edit the description
* copy all
* close editing
* create a new card
* edit the description
* paste

It is very long as this needs lots of tiny steps. => A lot of time could be saved here.

**Describe the solution you'd like**
The meatballs menu ("...") of the card may add an action/icon "Clone card".
The result may be a second card immediately created right below the original.
Optionally, the newly created card could be in editing mode.

**Describe alternatives you've considered**

*Button location*
The "Clone card" action/icon could be located in the card detail on the rightmost area/column of the browser.

*Where to*
When cloning a card, options could be shown to the user:
Clone card to:
* same board:
  * same stack:
    * below original card
    * above original card
    * top of stack
    * bottom of stack
  * other stack:
    * top of stack
    * bottom of stack
* other board

But that may be be too much, smart defaults are cool, and principle of least surprise is better.

*Content*
It could be possible to let the user choose what to clone:
* tags
* assignees
* date
* attachments
* comments
* timeline

**Additional context**

**Comment by Nils160988** [comment]
An even easier solution would be to enhance the "move card" dialog with a checkbox to copy.

So, change the "move card" option to "move/copy card" and then have an option to copy instead of move when choosing the target location.

**Comment by jakobroehrl** [comment]
I can do this after https://github.com/nextcloud/deck/pull/1777 is merged

**Comment by the-cloud** [comment]
@jakobroehrl I'm in a great need of this feature, and lack of knoweledge of how to do that. If you would like to review your interest in implementing this feature I would greatly appreciate that.

Well, if anyone is interested in coding this, that would be awesome. I could send some euro or crypto as thank you.

**Comment by osm-frasch** [comment]
I also think that it would make work a lot easier and faster if you could simply copy cards.

**Comment by TalusUnheil** [comment]
Hey there! I am also very interested in this function. I have created a card as a template, which provides a checklist, as well as a Markdown formatted skeleton for the history per card.
If I could just clone instead of copy'n'paste, that would be very helpful.

**Comment by pete-at-future-campus-ruhr** [comment]
Hey guys, first off, thanks for all the great work! Is there a way to contribute to the feature? I am not a programmer, but I could offer to create syntax in form of a wireframe.

If no help from a noob is needed, maybe there is a chance to know where this feature stands in terms of priority?

Useful features in terms of UI would be e.g. alt+drag on a card to create the duplicate, and the ubiquitous ctrl+C / Ctrl+V for copy and pasting stuff. I am new to the github community, so if I am smehow overstepping let me know :)

**Comment by weeman1337** [comment]
I am currently working on this. The „move card“ card menu item will change to „copy/move card“ and the dialog will contain an additional „move card“ button.

**Comment by hoshi411** [comment]
This issue was opened in 2020 and it is now 2023.  The ability to copy a card is crucial.  Without it we can't invest in building cards when all of the info contained in the carefully crafted cards has to be manually copied to a new card every single time.  It is impossible to create cards as templates that can be quickly duplicated in mass which is the very reason for using a kanban system in the first place.  How is this not no. 1 priority?  How is it 3 years later and this doesn't exist yet?  Kanban is impossible to use without this feature.

**Comment by HonkXL** [comment]
We use in our company a version from weeman1337 with the clone- and copy-feature (and with categories for the boards). Both works very well. Our users are very happy with this, because copying contents of cards with the clipboard is very bad. We tried to push the categories feature, but the discussion about the was more expensive than the development....

**Comment by osm-frasch** [comment]
Will the Weeman version then also end up in the App Store or be merged with the actual Deck app?

**Comment by weeman1337** [comment]
I will prepare a pull request soon

**Comment by daiseco** [comment]
Is there already something new on this issue we need the function urgently as well :)

**Comment by osm-frasch** [comment]
As a feature enhancement, it would also make sense to have the option of adding a short description text to a board. Just as with group conferences in the Talk App. This would make it easier to communicate the purpose of a shared board.

**Comment by osm-frasch** [comment]
Haven't heard anything about this for a long time. Is there any progress?

**Comment by weeman1337** [comment]
Yes, still buried in my Deck fork. I need to find some time to create a proper PR :neutral_face:

**Comment by 0xA1F1E** [comment]
I stumbled upon this issue when I was searching on google for a way to copy cards. Really hoping this will become a feature! I'm also in the same boat as @blubbel42 and have cards with checklists in them that I would like to copy.

**Comment by gonzalo** [comment]
Here I am also a big fan of Deck that would LOVE to be able to duplicate Cards. for example I use a lo the markdown style to add checkboxes lists. I would like to duplicate cards to repeat procedures.

**Comment by viceldan** [comment]
Yes please :-)
That would help us in many ways.
For instance we use template cards (in a templates list) to spawn similar tasks and send them to our coworkers.

**Comment by frtosc** [comment]
I really appreciate Deck. This is the feature I miss more.

**Comment by hoshi411** [comment]
AND whatever you do, do not half ass this function!

When you finally get around to implementing the duplication of a card make sure that there is the option to "mirror" it!

Yes, mirror it.

That means that one card can be mirror/synced in one deck and another.

It is a complete mess for the user when they are forced to manually update all of the data in a card that is duplicated in various decks.  The user makes a change in one deck and then they have to go find that same card in another deck and another and make sure the data is all the same.

No.  Do not put the users through that.  

This is 2023 guys.  The basics here.

**Comment by putt1ck** [comment]
> When you finally get around to implementing the duplication of a card make sure that there is the option to "mirror" it!
> 
> Yes, mirror it.
> 
> That means that one card can be mirror/synced in one deck and another.
> 
> It is a complete mess for the user when they are forced to manually update all of the data in a card that is duplicated in various decks. The user makes a change in one deck and then they have to go find that same card in another deck and another and make sure the data is all the same.
> 


I think that would be a new RFE. Duplication of a card creates a copy; takes the elements of an existing card stored in a current board/list and makes a new identical card in a different board/list, inheriting the features of that new location. You're asking for cards to be entities in their own right, independent of any board/list (or even Deck?), but referenced within the board/list; you then get into a whole mess with existing board level config - boards can have different permission sets and therefore users that all cards inherit and similarly different tags. 

So implementing a sync card feature requires some thought about how those board level features would be dealt with; who can create a synced card; what happens with permissions and tags; what happens if a card is synced by a user who then no longer has appropriate permissions to one or more locations for the card; what happens to tag sets; would the card be able to be edited in any board, or only in the originating board. And so on.

**Comment by blubbel42** [comment]
> AND whatever you do, do not half ass this function!
> 
> When you finally get around to implementing the duplication of a card make sure that there is the option to "mirror" it!
> 
> Yes, mirror it.
> 
> That means that one card can be mirror/synced in one deck and another.
> 
> It is a complete mess for the user when they are forced to manually update all of the data in a card that is duplicated in various decks. The user makes a change in one deck and then they have to go find that same card in another deck and another and make sure the data is all the same.
> 
> No. Do not put the users through that.
> 
> This is 2023 guys. The basics here.

I would second what @putt1ck said. This is totally NOT what I would search for in copying cards. Making cards sync/mirror each other would be a totally different thing, not event talking about permissions etc.
This should totally be a new Feature Request. 
Copy a card means just that. Make a copy, work with it elsewhere or create hundreds. Like from 1 Template card do 100 instances of the same task and move them to the right boards/persons/whoever.

**Comment by schwankd** [comment]
So how is it going, i think we all really need this feature. Its pretty complicated to use Decks for repeating Tasks like Video Projects. Its not really possible to use a Board as a Template.
Greeting Schwank

**Comment by schwankd** [comment]
So coping Boards (with the cards in it) would be enough for now.
Thank you in advance

**Comment by colletda** [comment]
So @weeman1337, how's the standing of NC Deck copy-cards?

**Comment by Shadowstreik** [comment]
I would very much appreciate the ability to copy cards. Currently, it's work to do it, manually, copy and pasting contents, repeatedly. How soon shall this enhancement be released? Thank you.

**Comment by criro** [comment]
Yes it would be really helpful, it seems like an absolut basic feature to copy/klone a card.

**Comment by Openpony** [comment]
Hello ! 
We use Cards as template and need a feature to be able to copy this template as a new card in the same board. Is there any chance to get this feature that everyone here was asking for ? 
Many thanks in advance !

**Comment by gnilebein** [comment]
I hope that things will continue here soon. An alternative would be to extend the Text Template App with Markdown support. This would make formated text templates for decks possible.

There is a proposal for this, but I don't know if the app is currently being developed further:

https://github.com/nextcloud/text_templates/issues/8

**Comment by Shadowstreik** [comment]
Currently, the only workaround *I* know of is to create a *TEMPLATE CARD* that is filled out with all of the necessary data. Then, a new card would be crated and the contents of the TEMPLATE would have to be copied over into the new card. It is how I do my new cards. :\

**Comment by avatar1024** [comment]
This feature would be very useful indeed!

**Comment by viceldan** [comment]
... as a matter of fact, I gave up on this one.
I removed deck from my nextcloud and chose to implement a separate wekan server in my environment.
It has everything that I need (and more...)
In my humble opinion, this task is taking too long - it's been nearly four years now.

**Comment by osm-frasch** [comment]
@viceldan 
I think most good projects either lack developers who want to get involved or lack the seriousness to continue the project quickly. Nextcloud itself probably doesn't have the capacity and has to prioritise. There are several similar examples with Nextcloud apps. I had another similar experience with the "Approvals" app. Thanks for the tip about Wekan

**Comment by BeFreeNowHere** [comment]
Yes 4 years an still not having such a basic and easy to implement feature is really too much.
I think the main problem in Open Source Projects is that the progammers get payed for what they do.
This would help them to spend more time on Open Source Projects.

So we should create a system, where people can ask for a feature.
The programmers then make a guess of how much work it would cost them.
Then they say we need e.g. we need 500$ to get this done.

Then people can donate for exactly this feature until the 500$ are reached.
Then they can begin to implement to get this done.
If there are 500 users and all of them donate 1$ the new feature is payed.
But sometimes people/companies would be willing to pay the whole feature alone so that it goes faster by a payement of 500$

What do you all think about that?

**Comment by Jacques-Olivier-Farcy** [comment]
Any news on this feature ?

**Comment by keithkhl** [comment]
How much does the dev wants to me paid for this minor upgrade?

**Comment by reidellawfirm** [comment]
> How much does the dev wants to me paid for this minor upgrade?

I would help sponsor this feature.

**Comment by DinoBellini** [comment]
> AND whatever you do, do not half ass this function!
> 
> When you finally get around to implementing the duplication of a card make sure that there is the option to "mirror" it!
> 
> Yes, mirror it.
> 
> That means that one card can be mirror/synced in one deck and another.
> 
> It is a complete mess for the user when they are forced to manually update all of the data in a card that is duplicated in various decks. The user makes a change in one deck and then they have to go find that same card in another deck and another and make sure the data is all the same.
> 
> No. Do not put the users through that.
> 
> This is 2023 guys. The basics here.

**Comment by DinoBellini** [comment]
Create new hard linked card or symbolic linked card #6083

**Comment by marcoambrosini** [comment]
Hi all, there's an issue with the selected input field upon opening the dialog, possibly because it is activated before the component is rendered. 
I think that this is easily solvable by not auto-activating the input. Which will also allow a better understanding of what this dialog does (Currently the open select blocks part of the dialog)

<img width="510" alt="Image" src="https://github.com/user-attachments/assets/d4b7c823-e5db-4a08-8b04-6150222262db" />

**Comment by juliusknorr** [comment]
@grnd-alt Can you check taht?

**Comment by pagaille** [comment]
Hi. On an old system I'm stuck with NS 27. Any chance I get the latest version of this plugin installed (manually) ? The store only shows me the V1.11.7.
