### ISSUE TITLE
Developers and project maintainers don't realize the community loves them and their hard work

### ISSUE THREAD

**Issue by bsherwoodofdaptiv** [nextcloud/deck#1864]
Despite the complaints and the difficulty of releasing a new version, the developers don't seem to be realizing that there are a great number of users who really appreciate what they are doing and where they are taking the application.

Expected outcome:
 - Developers feel good and proud of the work they have done.

Stay safe. Stay Healthy.

Great work!

**Comment by agentlibre** [comment]
Yes, thank you for your work! 🎯

This app is likely to turn into THE central pillar for project management within the NextCloud environment, especially for a decentralized organization like mine! New dots connected to the other Nextcloud modules (tasks, mail, calendar, etc.), and this goes to the moon! 🚀

Keep it up! 🙏🏼

**Comment by Nyco** [comment]
Indeed, maybe it is not obvious enough:
We love you, and we love your work!!! ;-)
As a proof, we use it everyday.

Version 1.0.0 has been a huge improvement, Thanks a lot for this!
We send you all the positive energy to make the next release even better!

**Comment by TtuxX** [comment]
Hello to all the developers and contributors of the Deck application!  :)

I would just like to take this opportunity to express myself on this subject without counting my words to express my gratitude (and my positive opinions, which will probably also be those of most of us).

I wanted to tell you like the others here that you've made Deck a great application, that the work you're doing on it is considerable (we can see it) and that we all see and appreciate how the application gets even better and better with each new release.

Your work is really incredibly useful to us. This application is so useful to me that Deck has become the only task/project management application I use.

To be honest all these last years I haven't found anything that suited me, that was flexible and pretty.
The Deck application is pretty, simple, powerful, yet free software.
It syncs perfectly on smartphone with the Deck application for Android. The Deck android team is also doing an incredible job, the application is improving dramatically week after week thanks to their hard work and it feels like it's Christmas with every new release!

I use the Deck application in the browser and on the smartphone for literally everything I need in my daily life, ranging from just using it for my shopping lists to managing all my day-to-day professional work or managing my hobbies. 

I thus would like to take this opportunity to thank here all the developers and contributors to the Deck application and hope, through these few words, to have also contributed on my side to show you how much what you do for the community is appreciated each and every day.

Thanks again for all your tireless contributions and keep up the great work because you can rest assured that you are making more and more extremely happy Nextcloud Deck users with each new release. <3

Stay safe.

**Comment by desperateCoder** [comment]
Well, that was unexpected.

You're very welcome, buddies! Thank you so much for these kind words! :heart: 

![grafik](https://user-images.githubusercontent.com/6911132/81787166-ed2e6200-9500-11ea-88a3-e08620eab4b7.png)

I'd also like to thank @juliushaertl, @David-Development, @tobiasKaminsky and @stefan-niedermann for the great job they have done and still do, to make this project possible and successful.

And to all others: Thank you for using our software and for the appreciation! Stay safe!

**Comment by Dubidubiduu** [comment]
Also from time to time users are a bit churlish when posting issues, but actually love that piece of software, which is making their (ngo)-work possible.

Thank you so much.

**Comment by ramezrafla** [comment]
I wanted to chime in, as I opened an issue #1846 recently where I was disappointed with all the bugs in v1.0

As a community we are grateful. So a big thank you to developers.

But we need to add that there is an expectation of quality in the product. If it is the apps store, we expect it to be fully functional and with little to no risk in upgrades. We had to manually roll back to a previous version to make things work. 

> If a version is not ready for prime-time, then wait a bit, share it with the community for testing. But don't release it as production. We are all partners in this community, and we each have an expectation from each other.

Thanks for all the hard work. This app is a critical part of NextCloud for the long-term.

**Comment by McAviti** [comment]
This should be ticket #1

**Comment by vittokox** [comment]
I think this issue has been understimated. I just want to say you a big THANK YOU for all the hard work you do everyday. 
Take care of you and your families in this difficult times.
Greetings from Valparaíso, Chile!

**Comment by ediazcomellas** [comment]
This issue is a top priority. 

I want to thank every developer. Your work is greatly appreciated. Nextcloud and all it's apps are becoming a central piece in IT infrastructure. Your work is helping people to work smarter. In 5 years every company will have it's nextcloud for internal files, and that will be thanks to you.

Great software is made by great people. That is you.

Thanks a lot from Spain.

**Comment by S0QR2** [comment]
Your work is appreciated and V1.0 is a big step. I put the evaluation of deck off to the side in favor of wekan, beeing a bit sad as we use NextCloud and Talk quiet a lot. Now with V1.0 we can make the switch over to Deck with minimal feature loss. It captures the essential parts of a kanban board really well. Thank you again!

**Comment by alexbijma** [comment]
Dear developers,

Thanks for the work you've done sofar. It's great to see that there is a new version of Deck, next to Forms and Flow is Deck the app which is, in my opinion, very important to make Nextcloud really a competitor with their opponents. 

Deck is one of the apps which is obviously needed for companies and individuals to keep priority and overview on their work.

Please continue the good work!

I'm sorry that there is so less time to support you in testing and cooperating with the new versions/functionalities. But if there are questions are you need input from users, please let me know. I would like to support where possible.

Thanks thanks for the hard work!

**Comment by juliushaertl** [comment]
Thanks a lot everyone for the kind words, I really appreciate that.

A huge thanks from my side goes out to everyone who is contributing to the app by providing patches, reporting issues, proposing features, testing, translating, using it or talking about (and everyone I forgot). This would never be possible without all of you. This is the magic of free software. :heart: 

Let's close this as a wont fix, but feel free comment if you still encounter this "issue". :grin:
