### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by V3R4DE** [nextcloud/deck#187]
Great plugin,

please create an android app for fast access on mobile device.

Greetings!

**Comment by juliushaertl** [comment]
I guess this will happen some time in the future, but this is not part of the repo here.

There has already been some discussion, as an app will require an API first. See: https://github.com/nextcloud/deck/issues/83

**Comment by thomas-mc-work** [comment]
Maybe you can reuse an existing OpenSource kanban app like [Kandroid](https://github.com/andresth/Kandroid) and "simply" add an implementation of your API. That would save a lot of time.

**Comment by mat-l** [comment]
Are there any updates about offering an App for the great Nextcloud Kanboard plugin? I'd love to see one.

**Comment by juliushaertl** [comment]
Nothing new here, sorry to tell so. We need to finish the rest api first. :wink: 

Progress of that is in #83 / https://github.com/nextcloud/deck/pull/271

**Comment by beta2k** [comment]
So Deck cannot be used on a mobile as of now, is this correct?

**Comment by benyanke** [comment]
The workflow is surprisingly usable in a mobile browser in my experience.

But yes, for mobile native, it's not yet supported.

**Comment by joeldeteves** [comment]
This app is very useful, and it is such an integral part of many organizational structures. Therefore it should be considered for adoption into the Nextcloud project (and thus the official NextCloud mobile app). Tagging @jancborchardt

**Comment by benyanke** [comment]
hear hear! Also critical to my workflow as well.

**Comment by hitam4450** [comment]
Well, same here! It would be a great extension of the Nextcloud mobile app!

regards, hitam4450

**Comment by juliushaertl** [comment]
> This app is very useful, and it is such an integral part of many organizational structures. Therefore it should be considered for adoption into the Nextcloud project (and thus the official NextCloud mobile app). 

The app is part of the Nextcloud project, but the Nextcloud app you are refering to is just a files app, so I don't see integration of any other nextcloud app into that happening.

Since we have a REST API since the last release, it should be possible for community people to start developing something, but since I'm not an Android/iOS developer we need people who are up for doing that. :wink: 

Maybe @stefan-niedermann   wants to get something started, as mentioned in https://github.com/nextcloud/deck/issues/83#issuecomment-296599894 ?

**Comment by stefan-niedermann** [comment]
Yeah, i am definitely interested in developing an android app.

I will let you know if i have news for you :)

**Comment by bsherwoodofdaptiv** [comment]
I will say this. I love the work done so far, and the latest update as well.

I am currently stuck using Trello, simply because of the android (mobile) client. It makes life so easy.

But.. Yes, an API layer has to be written to allow clients to be able to push and pull data in order to build a mobile app (regardless of platform). That is an expensive endevour for any project. So, we all wait patiently while the very cool work already being done on this project continues.

The web page variant on a phone renders, but it not really servicable as it stacks all 'stacks' above each other. I have really long stacks in my Trello account. So that may a problem. And.. I hate having to log in every time I ant to shuffle cards.

**Comment by stefan-niedermann** [comment]
The party continues at https://github.com/stefan-niedermann/nextcloud-deck/

Please note: **This project is pre-alpha and not feature complete**. It is currently able to display boards, stacks and cards, but you have to be online. Offline-support is planned, editing is planned. The Github repo is only a preview, we will add builds for Play Store and F-Droid as soon as we have reached a reliable level.

**Comment by jancborchardt** [comment]
Wow @stefan-niedermann, you rock! :man_singer:

**Comment by stefan-niedermann** [comment]
Credits to @desperateCoder

**Comment by desperateCoder** [comment]
<3

**Comment by jancborchardt** [comment]
@desperateCoder no worries! I’m there to help regarding design questions, so please feel free to @-mention me in any issues in the Deck Android app repository where design input is needed. :)

**Comment by desperateCoder** [comment]
Thank you, this could be coming handy! By design you mean UI / UX? Or application design, architecture or something else?

**Comment by stefan-niedermann** [comment]
He means UI / UX ;-)

**Comment by bsherwoodofdaptiv** [comment]
This is currently a 'dev only'  side load app, correct?

Happy to see something is coming. Greatly appreciate the efforts you are putting into it.

**Comment by desperateCoder** [comment]
@bsherwoodofdaptiv won't call it dev-only, but currently I wouldn't recommend it for anyone. If you test it and you find possible improvements, you can tell us and we'll appreciate that! We are working at it any time we can, so stay interested and visit this project here and then, i am pretty optimistic this could get something useful for you guys out there.

Thanks for your interest!
