### ISSUE TITLE
Add Internal link Clipboard

### ISSUE THREAD

**Issue by agentlibre** [nextcloud/deck#1871]
I sometimes need to draw the attention of my team to a specific board, or even a specific card. However, it seems that there is no simple "internal link" (Only works for users with access to this folder) to be shared with them.

I would appreciate having a internal link clipboard button such as these you find to share folders or files (also existing in Nextcloud Forms or Appointments):

![Screenshot from 2020-05-12 12-29-39](https://user-images.githubusercontent.com/60295112/81674431-708e7b80-944d-11ea-9c3c-8f6410c4b942.png)

Would it be possible to replicate this feature for Deck? I don't think it's even necessary to have a public link at the stage; a mere internal link would already be a good step forward for a wider adoption of this module.

Many thanks for working on this app! 🙏🏼

**Comment by juliushaertl** [comment]
You should be able to just copy the URL that is currently show in the browser. This will work across different users if a board is shared and will navigate you directly to the card.

**Comment by agentlibre** [comment]
Thanks for the tip, I will use it!

I still think it would be a good add-on though. Copy/paste the URL doesn't work for all other NextCloud apps; hard to know when it does and when it doesn't. For a common user point of view, I believe a standardized/unified UX/UI all over NextCloud modules would be preferable.

**Comment by stefan-niedermann** [comment]
In this case we should fix those other apps you mentioned (or open issues in their repositorys) because this *is* the *standardized* way for web applications 🙂

**Comment by juliushaertl** [comment]
> I still think my suggestion would be a good addition though. Copy/paste the URL doesn't work for all other NextCloud apps; hard to know when it does and when it doesn't from the common user's point of view. I believe a standardized/unified UX/UI all over NextCloud modules would be preferable.

Ideally yes, but please open issues for that in the related app repos. For the files app there is some progress already in https://github.com/nextcloud/server/issues/12470

**Comment by paulRbr** [comment]
> You should be able to just copy the URL that is currently show in the browser. This will work across different users if a board is shared and will navigate you directly to the card.

Hi there @juliushaertl, indeed sharing the current URL will work for users that are already logged in into Nextcloud.

However, there is still an existing issue with the Deck application when you share an « internal » deck to users that are **not yet logged in nextcloud**. If you share the URL `/apps/deck/#/board/1` to an unlogged user, after login, the user will land on `/apps/deck/` instead of  `/apps/deck/#/board/1`.

I believe the Deck application should “remember” the original URL when a guest user visits the page and tries to login, so he can be redirected to the correct board **after login**.

Right now I can't share my boards easily to the correct person, because they never land on the board I share to them!

Am I doing something wrong? How can we achieve this “internal link” sharing, even after login?

Thanks for your help!
