### ISSUE TITLE
UI/UX: Hovering should highlight item

### ISSUE THREAD

**Issue by simonspa** [nextcloud/deck#1880]
Hovering an entry on the board list as well as a card on a board should highlight the item by changing the background color. This helps to spot the item about to be selected.

On Nextcloud files, hovering an entry on the files list looks like this:

![image](https://user-images.githubusercontent.com/1677436/81842298-12948d80-954c-11ea-842e-28520b99d9ab.png)

while no highlight is added to the list item on Deck:

![image](https://user-images.githubusercontent.com/1677436/81842285-0d374300-954c-11ea-8703-015c578e6d4b.png)

(I'm sorry the mouse pointer is not visible in screenshots :))

Optimally also cards could be highlighted when hovering them - the interaction would feel a lot more fluid.

**Comment by stefan-niedermann** [comment]
I agree with the hover effect on the boards list, but i think the background color of a card should stay the same when one is hovering it. I think we can improve the haptic on other points: for example blur the shadow around a dragged card:

![grafik](https://user-images.githubusercontent.com/4741199/81847321-b9305c80-9553-11ea-969b-b7e49b1b4e4c.png)

Instead of changing the color, we should signal the user, that (s)he can actually grab the card by using `cursor: grab;` / `cursor: grabbing;`.

![grafik](https://user-images.githubusercontent.com/4741199/81847513-fc8acb00-9553-11ea-9bb8-39a074ace3ce.png)

**Comment by simonspa** [comment]
I fully agree - coloring the whole card is too much area and will just flicker and distract. Also, the buttons themselves would not show properly. I like your suggestion with the shadow, that looks quite good.

Concerning the cursor: do you think using `grab` over cards would confuse users and distract from the possibility of clicking it for opening the sidebar?

**Comment by stefan-niedermann** [comment]
We can also think about using `cursor: pointer` - i think both variants are better than the usual `cursor: default` because imply that there is some kind of action possible and this is not a readonly view.

Personally i think, that the "click" action is usually discoverable and one of the first things that users will try, so `cursor: grab` should be fine.

Though when the card is actually *dragged*, the cursor `grabbing` should definitely be used.

cc @nextcloud/designers

**Comment by juliushaertl** [comment]
@simonspa Using it for some time now I actually think we should switch the gray shades of the hover and current card state so that the current card is highlighted stronger than the hover focus. Hover should rather be a decent indicator imo. What do you think?

**Comment by juliushaertl** [comment]
Regarding the grabbing cursor, I agree that we should use grabbing during drag. I'm also not sure about the grab icon on the stack headers anymore, since the primary action there is still the click to edit the title. Maybe we should thing about adding a drag handle icon on hover and just give that the grab cursor?

Trello actually doesn't indicate that but uses a pointer on the whole card, which I tend to say it also enough.

**Comment by simonspa** [comment]
Hm, good point - current card should also be highlighted, you are right. We could use

```css
box-shadow: 0 0 5px 0px var(--color-box-shadow);
```

for hover and

```css
box-shadow: 0 0 5px 2px var(--color-box-shadow);
```

for active? I'm not sure actually the difference between inactive and hover will be noticeable. I found that simply adjusting the blur doesn't do much visually.

**Comment by juliushaertl** [comment]
Different states implemented on master now:

![image](https://user-images.githubusercontent.com/3404133/99237729-2f5e9600-27f9-11eb-8c52-56241322c9b4.png)
