### ISSUE TITLE
Update broke markdown checklists

### ISSUE THREAD

**Issue by qoheniac** [nextcloud/deck#1902]
I used to write checklists like this:
```
[ ] Item 1
[x] Item 2
```
Now they only work like this:
```
- [ ] Item 1
- [x] Item 2
```
So I have to manually edit all checklists I ever wrote to work again.

P. S.: I cannot provide a Deck version number as I don't know where to find it as a non-admin user.

Edit: I found the version number in the HTML page source. It's 1.0.0.

**Comment by juliushaertl** [comment]
The main issue with this is that it is not standardized like this. Since we aim for using the same editor as Nextcloud text at some point, where we basically stick to the commonmark standard with the extension of GFM for checkboxes, we will not be able to support this any longer:  https://github.github.com/gfm/#task-list-items-extension-

Closing as a wont-fix therefore.
