### ISSUE TITLE
Edit description of card as a sub-window / popup card

### ISSUE THREAD

**Issue by NukeManDan** [nextcloud/deck#1941]
**Is your feature request related to a problem? Please describe.**
When I create a card, I want to edit the description easily and on the fly. At the moment I have to click on opposite sides of the screen multiple times to get there. It takes time and is complicated.
![deck description edit](https://user-images.githubusercontent.com/35669742/82600018-74677f80-9b6a-11ea-9c93-24868b299fa8.gif)

**Describe the solution you'd like**
Ideally a newt popup card would appear on clicking on card that I could edit basic fields (tags, description, members assigned) that appeared right next to the card or over it, not in a sidebar. (trello has this behavior, but the window is full height and centred, possibly much smaller, pointing the the card itself)

**Describe alternatives you've considered**
using trello :sweat_smile: 

**Additional context**
love the progress. Getting closer to a usable alternative with these kind of UX improvements!

**Comment by juliushaertl** [comment]
I agree that sometimes a modal would be good to both provide more space and a shorter way when moving the mouse, but showing it will actually remove the context of the other cards that might still be relevant to see for an overview.

cc @nextcloud/designers

**Comment by stefan-niedermann** [comment]
How is the calendar app solving this? I think they have a sidebar *and* some kind of modal too, no?

**Comment by juliushaertl** [comment]
> How is the calendar app solving this? I think they have a sidebar and some kind of modal too, no?

Calendar has an optional modal, but that is more like a quick-edit view with limited options:

|     |     | 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/3404133/83858307-97726180-a71c-11ea-8089-9adf986beb70.png) | ![image](https://user-images.githubusercontent.com/3404133/83858316-9b05e880-a71c-11ea-99c5-c5b930117454.png) |

**Comment by juliushaertl** [comment]
We actually discussed a focus mode for editing cards to have more space for the description in #1264 so I think it would make sense then to also provide the other card options there. Closing as a duplicate therefore.

**Comment by nousernameavailableanymore** [comment]
Ok, so the solution here is pretty simple and based on the "simplified editor" of the calendar app (as mentioned here before and also in my request #2031 :
just take the top part of the card details (details, attachments, comments, timeline) and just copy it one-to-one into a pop-up window.

Then add a little pencil symbol for the description at the bottom of that window.
When someone clicks it, the whole pop-up window turns into the "editor" field for the card description, so there is enough space.

If someone wants to go back, just add a little back button at the top of the pop-up that is now showing the card description.

Design-wise its pretty clear, straight forward and easy (since it already exists in the sidebar) and basically nothing would need to change / left out.

This would make the app look way more modern and at the same time more efficient to use.
