### ISSUE TITLE
3 dots menu is not completely displayed

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#2050]
**Describe the bug**
3 dots menu is not completely displayed

**To Reproduce**
1. Open left sidebar
2. Click on '....' of a board, which is at the bottom of the list
4. See uncomplete items in the 3 dots menu

**Expected behavior**
All items of the 3 dots menu are displayed

**Version**
Deck 1.0.3

![deck_left_sidebar](https://user-images.githubusercontent.com/34692335/85156163-f5915f80-b259-11ea-9b75-a4d15da56921.png)

**Comment by aktivde** [comment]
![Bildschirmvideo aufnehmen 2020-06-19 um 21 32 22](https://user-images.githubusercontent.com/65334274/85174348-7873e380-b275-11ea-9c08-8fc9fa347ea0.gif)

Same issue; in Chrome it appears at least as being scrollable. Maybe the issue is related to the removal of the global css rule?

However, it might be better to put some more effort into beta testing before officially launching a new version that is delivered to everybody? 1.0.2 already had this quite obvious right sidebar bug and now 1.0.3 has something similar in the left sidebar. ;-) I personally wouldn't mind doing some beta testing before launching but the release of 1.0.3 came a little bit too unexpected. Is there any beta testing routine that one can become part of?

**Comment by ecogit** [comment]
Same tiny issue on Firefox (77.0.1 with Ubuntu 18.04).
I'm willing to help testing as well.

**Comment by juliushaertl** [comment]
Upstream bug in the vue components library https://github.com/nextcloud/nextcloud-vue/pull/1160

**Comment by JoergPalmer** [comment]
Meant as a work around only ... you can navigate the initially not visible list using the arrow keys up + down.

Using Firefox (v77.0.1) here ...

**Comment by stefan-niedermann** [comment]
[Theoretically fixed](https://github.com/nextcloud/deck/issues/2104#issuecomment-653805695) by #2104 with

> I've fix finaly that in manualy adding a min-heigth of .app-navigation ul[data-v-b57f9b42]
but b57f9b42 is most probably changing at each css parsing

**Comment by lp177** [comment]
Finaly by allow overflow is better, sorry for the bad first idea @stefan-niedermann 
https://github.com/nextcloud/nextcloud-vue/pull/1183/commits

**Comment by cloud2018** [comment]
now it's ok: All items of the 3 dots menu are displayed:
![d2](https://user-images.githubusercontent.com/34692335/95453822-d551f180-096b-11eb-8a1f-9fcc845881a6.png)

**Comment by juliushaertl** [comment]
@cloud2018 Thanks a lot for reporting back, highly appreciated. :heart:
