### ISSUE TITLE
Display actual time/date in the timeline tab

### ISSUE THREAD

**Issue by devz3r0** [nextcloud/deck#2122]
As already requested at:
https://help.nextcloud.com/t/view-actual-date-time-in-the-timeline-tab

it would be nice, if somehow I can see on what date/time a event happened instead of XXX ago.

thanks Devzero

**Comment by ananyak19** [comment]
Hey can I work on this?

**Comment by ericloyd** [comment]
Not sure if this is the same as showing "09-Sep-2023" instead of "in a month" when seeing cards, but if not, can that be added to this request as well?  We do a lot of order tracking and "in a month" is neither accurate nor useful when the actual due date (as I write this on 26-Jul-2023) is 09-Sep-2023.  That's more than six weeks away, which is more than a month.

**Comment by arkhi** [comment]
I too am stumbling on this issue.

I need to remember to prefix the comment with the current date to find the information back later.
