### ISSUE TITLE
Project Relationships - exclude archived projects by default

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/deck#2331]
**Describe the solution you'd like**
When I am trying to "add to a project" connection, the list of available projects includes the archived projects. 

This introduces visual clutter as it shows projects that the user is likely not interested in. Instead of seeing one of their active projects, where the user could just quickly see it and click on it, they are required to filter out and find the correct project.  This can become annoying especially if you use standardized naming conventions. 

It would be better if only the active boards were shown with a flag for "include archived". 

**Additional context**

Here's an example - most of those projects are archived.
http://pix.toile-libre.org/upload/original/1601392463.png

EDIT: I think this would be part of the discussion for improving the relationships FE - see #2238

**Comment by stefan-niedermann** [comment]
Maybe we can display it but "extendable" (like in a `details` tag) or with an opacity of `.5`, so they are still reachable, but clearly separated from the other projects?

**Comment by aproposnix** [comment]
IMHO, the second option using opacity does help the user identify the active projects more quickly but you still have the potential for too much clutter in a menu.

**Comment by meichthys** [comment]
Maybe use the opacity along with moving archived projects to the bottom of the list?

**Comment by juliushaertl** [comment]
As the projects feature is superseded by related resources since Nextcloud 25 there are no plans to further work on this. As long as the feature is still there anyone is of course welcome to provide fixes through pull requests but I consider this part no longer maintained.

https://github.com/nextcloud/server/blob/stable27/config/config.sample.php#L2347-L2352 
https://github.com/nextcloud/server/issues/28320
