### ISSUE TITLE
Plan for migration of multiple enhancements.

### ISSUE THREAD

**Issue by Flamenco** [nextcloud/deck#2476]
I have made many updates to this project and would like to contribute. I am posting this to discuss the best migration.

Here some are the features.

- Updated look and fixed scrolling for individual columns.
- GroupBy boards.  Use other params to calculate virtual stacks and include cards from multiple boards
- Drag and drop to change values. (reassign, change tags, milestone, time to complete, etc)
- Filter Groups by stack or board.
- Added 3 more fields (product, component, and time to complete)
- Hide empty stacks filter
- Import and Export cards
- Generate a random color a minimum distance away from background color
- Process all cards in stack (add/remove tags, assign/unassign)
- Added column gaps to make it easier to scroll and/or move lists on a touch device

So the first step is to get the OK to add 3 additional fields to the card schema. (product, component, and time to complete). 

### Possible Upcoming Features
* User defined fields

### Screenshots
Here are some screenshots:
<img width="420" alt="Screen Shot 2020-10-24 at 11 10 16 AM" src="https://user-images.githubusercontent.com/819940/97085185-d9c40e80-15e9-11eb-9182-3ade804bad27.png">

<img width="1663" alt="Screen Shot 2020-10-24 at 11 08 55 AM" src="https://user-images.githubusercontent.com/819940/97085211-0710bc80-15ea-11eb-839e-8ed74f14203c.png">

<img width="1233" alt="Screen Shot 2020-10-24 at 11 07 36 AM" src="https://user-images.githubusercontent.com/819940/97085207-01b37200-15ea-11eb-8406-a0f6e502aa8b.png">

<img width="474" alt="Screen Shot 2020-10-24 at 11 10 02 AM" src="https://user-images.githubusercontent.com/819940/97085212-0bd57080-15ea-11eb-8a2c-67d7b2749811.png">

<img width="1014" alt="Screen Shot 2020-10-24 at 11 10 43 AM" src="https://user-images.githubusercontent.com/819940/97085216-10018e00-15ea-11eb-98cb-4297f5c513ab.png">

**Comment by Flamenco** [comment]
More grouping screenshots:

<img width="1050" alt="Screen Shot 2020-10-24 at 11 17 09 AM" src="https://user-images.githubusercontent.com/819940/97085278-8dc59980-15ea-11eb-8382-cd4928b597c6.png">

<img width="1042" alt="Screen Shot 2020-10-24 at 11 17 37 AM" src="https://user-images.githubusercontent.com/819940/97085279-8e5e3000-15ea-11eb-9492-33b32a73bca0.png">

**Comment by Flamenco** [comment]
And a setting to disable all of it.
<img width="316" alt="Screen Shot 2020-10-24 at 11 19 06 AM" src="https://user-images.githubusercontent.com/819940/97085318-ca919080-15ea-11eb-94b2-4743a09d3636.png">

**Comment by aproposnix** [comment]
I would be interested in knowing more about the "Use Developer fields". Will these fields be definable by the user or an admin or will the fields be predefined (like the ones in the screenshot)?

**Comment by Flamenco** [comment]
@aproposnix The developer fields are **product**, **component**, and **time to complete.**.  Disabling them hides them in the groupby and the item details.

It would be nice to have user defined fields!  I will put that in my backlog.

**Comment by Dubidubiduu** [comment]
This is awesome and would give deck a huge boost!

Wouldn't call those fields developer fields, since they're not development specific. Maybe they're just additional fields or so.

Looking forward all of this gets implemented.

**Comment by aproposnix** [comment]
@Flamenco I only just noticed the import and export buttons. Does this mean you have developed these functions or are these just placeholders? I think there is a bounty for this https://github.com/nextcloud/deck/issues/87

**Comment by Flamenco** [comment]
Import/Export is implemented, but it is all boards and replaces the current ones.  Mostly there so we can restore after we mess things up. ;)

I will start to roll out features in the next week or two.

**Comment by juliushaertl** [comment]
As mentioned via mail already, those features are definitiely worth considering and we would be glad to see contributions from you in that regard. However we should discuss them individually to see if they make sense for all users of the app. UI wise we would need to check back with @nextcloud/designers on the individual changes as well.

> Updated look and fixed scrolling for individual columns.

This will come already as part of https://github.com/nextcloud/deck/pull/2230 Feel free to open individual issues for smaller UI enhancement suggestions on top of that.

> GroupBy boards. Use other params to calculate virtual stacks and include cards from multiple boards

That would be the next steps in what we introduced with the upcoming cards view. cc @jakobroehrl 
Since that is quite a huge feature, could you split off your UI proposals into a separate issue for this one?

> Drag and drop to change values. (reassign, change tags, milestone, time to complete, etc)

Could you open a separate issue for this one? Especially some more detailed description on how this would word would be good there for the individual values.

> Filter Groups by stack or board.

This should also go into a separate issue.

> Added 3 more fields (product, component, and time to complete)

I'm not sure if we should have those hardcoded fields as they are targeting quite a specific use case. I'd prefer to go a more generic way for such additional metadata as described in https://github.com/nextcloud/deck/issues/1833

> Hide empty stacks filter

Makes sense imo.

> Import and Export cards

https://github.com/nextcloud/deck/issues/87 Feel free to just open a pull request with your changes in that regard.

> Generate a random color a minimum distance away from background color

Nice. :+1: 

> Process all cards in stack (add/remove tags, assign/unassign)

Makes sense, but we should make sure this is not overloading the UI.

> Added column gaps to make it easier to scroll and/or move lists on a touch device

Should be reevaluated after https://github.com/nextcloud/deck/pull/2230 and https://github.com/nextcloud/deck/pull/2166

So the quick summary is, contributions like those would be awesome, but we should split those into individual issues or PRs so that we can discuss and iterate over them.

In case you're interested I can also invite you to our deck developer chat, so we can have a more direct contact in case you have questions.

**Comment by mstyp** [comment]
My time tracking is telling me that I spent ~2 hours this week just on manually syncing cards between three different nextcloud servers. 

If you have these ready as a beta version or something please for the love of god make it public? Its such a pain to spend 20 minutes every morning *just* on making sure these different boards are all the same.

**Comment by Flamenco** [comment]
My company instructed me today to halt any further integration and additional efforts with this project, so I will be closing the previous pull request.
