### ISSUE TITLE
Issue with comment view

### ISSUE THREAD

**Issue by ruter68** [nextcloud/deck#2504]
Hi.
In Deck, in a card, when i add a comment (in TimeLine Form), i can't view it !
The comment don't appear in timeline form. This only appear the number of comments in card

**Comment by juliushaertl** [comment]
Thanks for your bug report. Please fill out the issue template to provide some more information about your setup and possible errors in the logfiles.

**Comment by hj-beckers** [comment]
Similiar bug: Comments don't appear under the comments tab, but only in the timeline. This must be an error in the latest 2 releases, because older comments (i.e. 20 days old) are still shown unter the comments tab. When I edit them, the same error appears: The comments tab is empty; the (modified) comment(s) is/are only shown on the timeline tab but without a updated date; it still says "modified 20 days ago".

Version:
openSUSE 15.2
php 7.4.6
nextcloud 19.04
deck app 1.2.1

Can I install an older version (1.1.x)?

**Comment by hri99** [comment]
Same issue in my system. It accours only, if linefeeds are in the comments. If I copy something with linefeeds in the comment-field, the comment is only shown in the timeline, without the linefeeds. 
If I delete the linefeeds, the comment ist shown correctly.

Nextcloud 18.0.6
Deck 1.2.1

**Comment by juliushaertl** [comment]
Fix pending with #2609 and #2611
