### ISSUE TITLE
Add undelete to stack [$10]

### ISSUE THREAD

**Issue by Spacebjorn** [nextcloud/deck#259]
Adding undelete to stack or at least a verification if the person is sure to delete a stack. happened to my org. that someone accidentally deleted a stack and it's too bad there's no way of getting it back or at least have a prompter to verify it.

Keep up the great work on the Deck. it's amazing!

**Comment by Aesculapius** [comment]
This definately needs to be in the product. Deck is great and the 3.0 beta also has great new features, but accidently deleting the whole stack just because you wanted to click outside the remark window to get that out of the way, cannot be wishful behavior. Is there absolutely no way of retrieving its contents?

**Comment by websafe** [comment]
This is a must. I came here after few hours with Deck exactly for this reason - accidental deletion of a complete stack with cards is too easy. There should be at least an additional prompt and a way to undo.

**Comment by bpcurse** [comment]
Just happened with our instance, too. A user deleted a huge stack and we had to manually repopulate some of the deck specific database tables from yesterday's sql backup dump. Another "thumbs up" for this really important feature!
As mentioned above by Spacebjorn and websafe a warning prompt if the user really wants to delete the stack would help a lot and should probably be faster and easier to implement than an undo feature.

**Comment by nekohayo** [comment]
The stack delete feature is "dangerous" (words fail to express my frustration at having encountered this today). I don't see why the delete button should even be present at all, especially if there are tasks within the column. Even then: what happens to archived/hidden tasks within that column/stack when it gets deleted? I hope they don't get silently permanently deleted too?

**Comment by GoetheG** [comment]
Hey @Spacebjorn,

cannot agree more with you. Everything should be done to avoid unplanned deleting. We also need functions that prevent the need of critical information technology support. Maybe Nextcloud should ask for the password?

I think that a trash bin should be implemented into Deck to give the users the ability to undo their (deleting) mistakes. This is a key problem that unfortunately makes it impossible for my organisation to use this app. We need a reliable solution for project management because we have no guy for information technology. There's nobody who can restore stuff manually for us. So this would be a disaster.

Really really hope that you'll find a reliable solution for this problem to make people wanna switch from Trello :).

Yours

**Comment by MangoSmoothie101010** [comment]
Hey,

The best solution seems to be the soft-delete + undeletion functionality in a "trash-bin"-style view.

I would like to start working on this now. 

Any pointers for good starting points?

Is a Cloud9 or CodeAnywhere instance already running to speed up onboarding?

**Comment by juliushaertl** [comment]
@MangoSmoothie101010 Glad to hear that you want to contribute. :+1: 

Not sure aware of any cloud9/codeanywhere setup for Nextcloud development, but you can find some documentation on how to get started here: https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html

For the deck app you basically need to clone the repo to the `apps/` folder and enable the app in the Nextcloud apps management. For deck you will need to build the javascript as described in https://github.com/nextcloud/deck#developing

For a starting point in the code, you might want to have a look at https://github.com/nextcloud/deck/pull/133/commits/2c63bfb4b8a7d5b0c22dc1d753e56d1dd08b61a9 which is the implementation of the undo functionality for boards.

Since we cannot just show the recently deleted stacks inside of the regular board view, I would suggest to add another tab to the board settings sidebar, where we add a list of stacks, including the deleted ones.

If you have further questions, feel free to ask either here or join our IRC channel on freenode.net: #nextcloud-deck

**Comment by MangoSmoothie101010** [comment]
I finally set the project up successfully.

First I tried on my work machine, then my personal laptop, then c9 and my last failed attempt was codenvy.

But now I just bought a server and I'm happily coding from my terminal, being connected via ssh.

I figured the best ide is free and is just a ctrl alt t away. :)

**Comment by MangoSmoothie101010** [comment]
Hm, so the boards are actually deleted once the cronjub went thru?

**Comment by MangoSmoothie101010** [comment]
Should the cards also be deleted after a while by a cron job like the boards? @juliushaertl

**Comment by juliushaertl** [comment]
@MangoSmoothie101010 Ideally yes, but we need to find a way to display deleted cards properly in the UI. I would suggest to first go for stacks and tackle the card deletion in a different pull request.

**Comment by MangoSmoothie101010** [comment]
I already implemented the soft delete and currently working on showing the
deleted cards in a newly introduced tab in the board settings sidebar.

I'm not planning on displaying them grouped by stacks, just sorted by the
date of deletion. Which stack they belonged to will be displayed though.

2018-07-10 13:38 GMT+02:00 Julius Härtl <notifications@github.com>:

**Comment by juliushaertl** [comment]
> I already implemented the soft delete and currently working on showing the
deleted cards in a newly introduced tab in the board settings sidebar.

> I'm not planning on displaying them grouped by stacks, just sorted by the
date of deletion. Which stack they belonged to will be displayed though.

Ok, that sounds good to me. We can also integrate that into the activity view later once #211 is implemented.

You also can open a pull request already, if you like to get some early feedback.

**Comment by MangoSmoothie101010** [comment]
@juliushaertl 
Just realized now, that this issue is about stack deletions. 

Will implement this after the card undo delete.

**Comment by juliushaertl** [comment]
@MangoSmoothie101010 :grin: We need undo for deleted cards as well, so no problem.

**Comment by juliushaertl** [comment]
@LemonAndroid Don't forget to claim your bounty for this one. :wink:
