### ISSUE TITLE
Headings don't follow core rules

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/deck#260]
Currently the text of all cards and stack headings is bold. In Nextcloud we always use normal (that is Open Sans Light) and bold only sparingly lile for clickable elements, usernames etc.

I'd recommend we change the font-weight to normal. Bold could be used for certain cases, for example to highlight a card when its sidebar is open.

**Comment by pixelipo** [comment]
@jancborchardt I've renamed this issue to address wider set of changes required to adhere to global styleguide:

- [ ] board title should be `<h2>` (because `<h1>` should be reserved for the (hidden) app title element
- [ ] sidebar header title should be `<h3>`
- [ ] stack title should be `<h3>`
- [ ] card title should be `<h4>` - core has no rules for this, so we might need to figure something out

That seems to be correct semantics, at least based on what other apps are using

**Comment by jancborchardt** [comment]
Yep, seems good. And yeah, I agree we need a h4 style. :)

**Comment by juliushaertl** [comment]
Fixed with #299

**Comment by jancborchardt** [comment]
Thank you @juliushaertl! :)
