### ISSUE TITLE
Use of snap.js in desktop view makes right sidebar disappear/glitch if you select text in the sidebar

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/deck#262]
If you drag-select text with your cursor from left to right in the sidebar, say from the description, it will prompt snap.js of the left navigation to move the content to the right, leading the right sidebar to disappear.

That's one reason why we don't use snap.js on desktop, only on mobile. ;)

We should probably fix this in core, but as Deck right now is the only app which overrides the mobile handling I'm opening it here. Probably a simple removal of the mechanic of content getting dragged to the right too far would fix it?

**Comment by juliushaertl** [comment]
cc @artemanufrij Since you already had a more detailed look to the snap.js stuff in https://github.com/nextcloud/deck/pull/190

I remember I also experienced some weird dragging behavior that shows the sidebar on mobile, but I'm not sure if that was in one of the other apps or related to deck. I need to check that again.
