### ISSUE TITLE
Export in excel

### ISSUE THREAD

**Issue by xrkolovos** [nextcloud/deck#2654]
Hello

I know that issue #87 exitsts, but i think that we should split this feature. Importing is hard, but exporting data is easier.
We should keep this issue, and maybe describe a way that this should work here.

**Comment by juliushaertl** [comment]
We should have a generic way of exporting first, then we can consider adding various formats based on that, so I'd love to just keep #87 for simplicity. Feel free to comment there so that we have the file format in consideration. However I'd rather go for CSV as it is easier to build and more widely usable than excel files themselves.
