### ISSUE TITLE
Cutted due date window in modalview 

### ISSUE THREAD

**Issue by 4tler** [nextcloud/deck#2704]
**Describe the bug**
Since update to v. 1.2.3. i have a cuted duedate window in the modalview.

**To Reproduce**
1. Go to modalview
2. Click on Due Date

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3404133/103699288-052c8780-4fa3-11eb-8a00-b4ec861041c5.png)

**Client details:**
 - Browser: chrome
 - Version: newest
 - Device: desktop

**Nextcloud version:** 20.0.4

**Comment by juliushaertl** [comment]
Can reproduce and added a screenshot

**Comment by reox** [comment]
As far as I understand that, the `<section id=tab-details>` has to have a different `min-height` property.
for testing, I set it to 100% and then the dialog is visible again.

I think this is set here:
https://github.com/nextcloud/deck/blob/cb05c30fbd72d41c8fe06ffa2631517991cae0c6/src/components/card/CardSidebar.vue#L189-L193

But I guess that setting `min-height:100%` is not the proper method to fix it? `min-height: inherit` will also not work because the container div has `height:100%`, but it has only `min-height:0`:
https://github.com/nextcloud/nextcloud-vue/blob/8ad992fbfd55e46457744a5a998dffe252008be8/src/components/AppSidebar/AppSidebarTabs.vue#L336-L345

I played around with `align-self:stretch` on the section, but the padding is in the way. 
I would be glad to fix this but unfortunately, I do not understand the css magic here 😅

**Comment by BKapelari** [comment]
> But I guess that setting `min-height:100%` is not the proper method to fix it? `min-height: inherit` will also not work because the container div has `height:100%`, but it has only `min-height:0`:

I think setting the 'min-height: 100%' should be a normal solution.
The second and maybe better solution is to set overflow to 'inherit' instead of 'auto' on the '#tab-details'

<img width="480" alt="Bildschirmfoto 2021-02-08 um 23 21 15" src="https://user-images.githubusercontent.com/4718590/107288814-5cbb8880-6a64-11eb-8f37-2cb5954d5ae2.png">

**Comment by reox** [comment]
I think the issue is indeed not the inner element, but the outer. If the description is longer than 100%, you get an extra scrollbar:
![double_scrollbar](https://user-images.githubusercontent.com/431045/107323176-1c7cfa00-6aa6-11eb-80b1-3a8ba156cd55.PNG)

When I add `overflow:auto; min-height:100%` to the `section.app-sidebar__tab--active`, it fixes both issues, however you will see a scrollbar even if there is no description. The issue is that due to the padding, the inner section does not fit:
![container](https://user-images.githubusercontent.com/431045/107323606-dbd1b080-6aa6-11eb-9ea7-4afa9d4a50a3.png)

You can change the padding to a margin on the outer div - but is that acceptable?

**Comment by reox** [comment]
This seems to be changed in NC 21.0.1 / Deck 1.3.2: Here, the calendar renders correctly, but you can see a scrollbar appear for the description field.

**Comment by artemanufrij** [comment]
Same here:
![image](https://user-images.githubusercontent.com/16517095/115730044-3d0adf80-a386-11eb-8c51-d6ead35cf329.png)

**Comment by reox** [comment]
> This seems to be changed in NC 21.0.1 / Deck 1.3.2: Here, the calendar renders correctly, but you can see a scrollbar appear for the description field.

okay, that was just a glitch because it rendered only correctly for a certain item.

I just added a new item without a description and the calendar is only 1/4 visible.

NC 21.0.2 / Deck1.4.2

**Comment by 4001982248998** [comment]
It seems to work again since today's update.

**Comment by bin101** [comment]
@4001982248998 which update?

**Comment by 4001982248998** [comment]
Sorry, I was referring to Deck's latest version 1.5.1. However, it introduced a nasty bug https://github.com/nextcloud/deck/issues/3292 which forced me to disable Deck.

![flameshot_2021-09-06_12-28](https://user-images.githubusercontent.com/2796469/132203572-e671a9da-ce6a-42e8-9d5d-8fec54cf5e9c.png)

**Comment by ilippert** [comment]
Just to check: did you, dear issue discussants, already consider whether it would be possible to set the date/time once date & time are picked, without the hazzle of an extra click on "ok"?

**Comment by reox** [comment]
It looks like since the update to nextcloud/calender 2.4.0, this bug has resolved? (I'm not sure if calendar was the issue, but this is the only thing which was updated for me)
The calender also looks different now (it has now buttons with a gray background):
![image](https://user-images.githubusercontent.com/431045/144051092-36a630d8-e6b3-4fb6-b5f6-9b28ff410dc3.png)
and renders correctly, even if no card description is set.
Using currently Deck 1.5.5 with NC 22.2.3

**Comment by 4tler** [comment]
it looks like it's not a problem anymore with the latest updates or?
