### ISSUE TITLE
Description Field: CSS / JS polish

### ISSUE THREAD

**Issue by aktivde** [nextcloud/deck#2739]
**Describe the bug**
When editing the description field it changes its width.

**To Reproduce**
Just edit the description.

**Expected behavior**
Size staying the same.

**Screenshots**
![Bildschirmfoto 2021-01-19 um 09 23 24](https://user-images.githubusercontent.com/65334274/105008051-08ab1e80-5a39-11eb-8384-de38d62743ae.png)
![Bildschirmfoto 2021-01-19 um 09 23 11](https://user-images.githubusercontent.com/65334274/105008043-0779f180-5a39-11eb-8019-01347c67522d.png)

**Client details:**
 - OS: Mac OS
 - Safari / Chrome
 - Nextcloud 21 Beta, Nextcloud 1.3 Beta
 - Device: Macbook

**Comment by stefan-niedermann** [comment]
I can't reproduce this issue on `Debian` with `Firefox 78.7.0esr (64-Bit)`.
Can you please be more specific about the version of Safari / Chrome and provide better steps to reproduce? I am missing some key information like

- Does this happen in the sidebar?
- Does this happen in the modal view?
- Did it work once?
- Is it dependent on the amount of characters or the length of the text you are entering?
- Do you already know what it is causing it (since you mentioned css polishing in the issue title)?
- Are you able to reproduce it on a Non-Mac-OS machine (if you have access to one) or with Firefox (since i couldn't reproduce it)?
- ...

**Comment by aktivde** [comment]
> I can't reproduce this issue on `Debian` with `Firefox 78.7.0esr (64-Bit)`.
> Can you please be more specific about the version of Safari / Chrome and provide better steps to reproduce? I am missing some key information like
> 
> * Does this happen in the sidebar?
– Yes it only happens in the sidebar
> * Does this happen in the modal view?
– don't know what that is
> * Did it work once?
– Yes. This is a new bug.
> * Is it dependent on the amount of characters or the length of the text you are entering?
– No, it already happens if you haven't entered anything. But it only happens during the time between writing and saving. After being saved it is displayed correctly.
> * Do you already know what it is causing it (since you mentioned css polishing in the issue title)?
– Yes: It is the "(nicht gespeichert)" that is too long for the div container and leads to shifting the paperclip icon into the next row. Then causing the description field to also shift along that icon
> * Are you able to reproduce it on a Non-Mac-OS machine (if you have access to one) or with Firefox (since i couldn't reproduce it)?
– Yes. Also happens in firefox (84.0.2). But it won't happen if your browser window is big enough to contain the "(nicht gespeichert)" in the sidebar. So to reproduce play around with the window size. I found out because the bug only appeared when using the laptop.
Safari version: 14.0.2; Chrome: 84.0.4147.89

> * ...

**Comment by stefan-niedermann** [comment]
Might be related to #2617
