### ISSUE TITLE
Can't Create New List After Deleting Card

### ISSUE THREAD

**Issue by ITCMD** [nextcloud/deck#2809]
Pretty Simple bug:
![image](https://user-images.githubusercontent.com/32961763/108242463-f0ebb680-711a-11eb-92b9-c2b19f4beecf.png)

Cant access the menu in the top right due to it being blocked by the "Card Deleted. Undo?"

- Deck app version `1.2.4`
- Nextcloud Server version `20.0.7`

**Expected Behavior:**
- Notification has a close "x" to dismiss the notification
- Notification dismisses itself

**Observed Behavior:**
- Notification cannot be dismissed without undoing the deletion
- Notification does not self-dismiss

**Comment by eldelacajita** [comment]
I came here to report this issue and found this report. The title could be more generic, like "Undo notification blocking other actions". Because that's what actually happens: any action that shows the "undo" notification blocks all actions that require clicking any of the buttons placed on the top right, You have to wait for the notification to disappear. 

See attached gif:

![Peek 2021-02-10 13-09](https://user-images.githubusercontent.com/2880679/126899045-442446e4-ab48-46a5-9588-dae75697655f.gif)

Not sure if this is specific to Deck or if it happens in other apps, though.

**Comment by juliushaertl** [comment]
Closing as those are upstream issues in the `@nextcloud/dialogs` library:

https://github.com/nextcloud/nextcloud-dialogs/issues/381
https://github.com/nextcloud/nextcloud-dialogs/issues/352
