### ISSUE TITLE
Timestamps on Created and Modified At Values

### ISSUE THREAD

**Issue by fuzunspm** [nextcloud/deck#2818]
Other than time diff between current date and created at value, like 3 months ago, please add an option to display exact creation/modification date like 12/01/2020 08:30 format on all values.

**Comment by juliushaertl** [comment]
Yes, those should ideally just have a tooltip to show the exact date.

**Comment by kartoffelheinz** [comment]
Getting bitten by this all the time, because there is no way to figure out what e.g. "3 months ago" actually means in terms of date, could be anything between 56 and 92 days from now.... And there are times when you need more than a vague estimate. 

Tooltip is a good solution - or just make it configurable what do show (for all occurrences where you display date differences).

**Comment by Spartachetto** [comment]
This would help for https://github.com/nextcloud/server/issues/25914

**Comment by kartoffelheinz** [comment]
It would be very nice if the Timestamps could be implemented for comments and history, too. Unfortunately, I am not firm with vue.js or the likes, so I cannot do it myself.

**Comment by jmbreuer** [comment]
Why is this closed? It seems to still show only approximate dates for me right now, see also #5728
