### ISSUE TITLE
Standalone application for Deck

### ISSUE THREAD

**Issue by lightnin** [nextcloud/deck#2873]
Like many users, I keep my instance of deck running in a browser tab so I can easily refer to it and update it frequently. This requires that I locate the tab and click it with the pointer or use shortcuts to advance back to a certain tab.

This workflow could be improved for me and likely many users if it were possible to run Deck as a standalone application on the OS, perhaps using a framework like Electron. This would make it easier to switch between Deck and the various other tools running on the OS.

This is excellent software, thank you to all contributors.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stefan-niedermann** [comment]
I am pretty sure that this will not happen.
There is [a well documented API](https://deck.readthedocs.io/en/latest/API/) which allows the development of native clients.
I am sure though, that Pull Requests to make this app a progressive web app are welcome (see [related issue for the Notes app](https://github.com/nextcloud/notes/issues/306)). This will allow also an installation and deeper integration into the OS.
Until then: Just open deck not in a new tab but in a separate browser window. Then you can find it in the taskbar instead of the tabbar (which solves your described issue) and use a bookmark as application launcher.

<small>Disclaimer: I am not working for, bor am i related in any way to the Nextcloud Inc. I am not the maintainer of this repository.</small>

**Comment by putt1ck** [comment]
I achieve a similar effect by using pinned tabs for Deck and other web apps I refer to frequently. If Deck is something you use so often that you want to reach it with a simple alt-tab (or whatever the switching is on your OS) then just launch it in a dedicated browser window (more or less what Electron is anyway)

**Comment by lightnin** [comment]
Thanks for the feedback, @stefan-niedermann and @putt1ck . The point about limited resources / need to prioritize makes sense, and thanks for the suggested workarounds. It occurs to me that one additional advantage of having a standalone model would be that it could operate offline, but being offline is probably a rather rare occurrence for most users. Closing this issue.

**Comment by stefan-niedermann** [comment]
For offline support see https://github.com/nextcloud/deck/issues/2207 - like i said, extending Deck to a progressive web app will implicitly result in a state which is really close to a native standalone app :slightly_smiling_face:
