### ISSUE TITLE
IDs for each card

### ISSUE THREAD

**Issue by JS-E** [nextcloud/deck#2906]
Hi there,

Love deck, super useful for a little project me and my family have going. Would be awesome to have an easily viewable id for each card so we can refer to each item when we discuss it.

If someone can point me in the right direction i'll happily add it myself.

Thanks very much and great work

Josh

**Comment by stefan-niedermann** [comment]
Hey @JS-E 👋 

the URL (see the address bar in your browser) already contains a unique ID. It looks something like this:

```
https://example.com/index.php/apps/deck/#/board/106/card/463
```

where `463` is the unique ID of the card.

Out of personal interest: I am curious what your workflow is and why the titles of your cards aren't unique? How are you using Deck that you can't talk like "Hey, the card 'hire craftman for repairing the roof' is still in the 'blocked' list. Do you have any news?"?

To be honest, i don't see an use case for the majority of the users which justifies the introdiction of an artifical new ID in the UI and would therefore propose to close this issue in favor of https://github.com/nextcloud/deck/issues/1833
This will bring user defined fields and implicitely provide support for your scenario.

**Comment by JS-E** [comment]
Ahh okay i can see that now, thanks for pointing that out 👍 The issue i'm having is that it might be more awkward for less technical people to know the id is in the address bar, and having that shown per card would be kinda cool in my opinion, or perhaps just a little setting to hide show id in the card view. I do understand your justification though, appreciate you clearing that up.

In terms of our use case, it's more for tracking boxes of items, so having an id would be quicker than going "Oh the box with toys and electronics" but we can just id them ourselves on the card title. 

That #1833 does seem like that will help with potential so i agree. Will that potentially have an autogenerated field for example? So incremented integer or something along those lines?

**Comment by stefan-niedermann** [comment]
> perhaps just a little setting to hide show id in the card view

Yeah 😄 just [a little setting](https://user-images.githubusercontent.com/4741199/111898640-a87c2d00-8a27-11eb-98ae-ecf46f46d607.png) 😄 

> Will that potentially have an autogenerated field for example? So incremented integer or something along those lines?

I doubt that, at least for the first iteration, though I am only the Android guy, so i really can't tell you...

**Comment by JS-E** [comment]
> Yeah 😄 just a little setting
haha fair point, mind you there are ways of making it subtle, unlike wget it seems.

> I am only the Android guy, so i really can't tell you...
Ahh cool, nice work with the app. I'd like to contribute at some stage

**Comment by pedro-nonfree** [comment]
somehow related to #622

the beauty of a unique ID per task is that:

- memorizing a number as a reference is the most efficient way to link to a material (just few characters)
- easier to link between tasks (duplicated, related) as github and most of up to day software forge does

but:

- following a task because of the title is not good idea because the title can change
- following a task because its URL (which includes the board ID plus the card ID) is not good idea because when you move the card from one board to another, URL does not work anymore (all past board ID plus card ID for a specific card should be aliases to refer to it), and I tested this with nextcloud 21.0.1 and deck 1.4.0

hence, right now I am not satisfied with a good way to follow the progress of a card in deck, and the ID approach, used in a lot of software that tracks tasks and incidents, would be the way to go. It should be as easy as creating a new tiny-table with an incremental number that just grows that id number and references all created cards

**Comment by Duskstrider** [comment]
I came here by googling and just want to second this issue.

It would be a great feature to have a visible ID on a card and to be able to find the specific card by just typing the ID into the search field. If this would collide with the standard search, one could use a simple syntax like "#123" for an ID based search.

Best wishes,
Martin

**Comment by juliushaertl** [comment]
The card id is unique but the links used might still contain the old board id.

We had a first attempt for this on activity emails with https://github.com/nextcloud/deck/pull/3611 to generate links that just use a card id.

Could you file a new issue for this and mention the specific places where the links are obtained from? This could also be the browser URL as there I can see that this is an issue. We may need some frontend logic to fetch the card details separately to check if the user still has access and then redirect to the current board the card is on.
