### ISSUE TITLE
Unable to select text in card description in 'Bigger View'

### ISSUE THREAD

**Issue by JS-E** [nextcloud/deck#2907]
When i view a deck card in the bigger view, i cannot copy the text that's in the description. Very minor but it's very useful in terms of speed when i'm using text information from the description.

Thanks 👍

**Comment by stefan-niedermann** [comment]
Would you please fill in the [issue template](https://github.com/nextcloud/deck/issues/new?assignees=&labels=&template=Bug_report.md) when reporting bugs? It is there for a reason. Otherwise we will have to play ping pong and ask you for the exact deck and nextcloud versions, the browser and its version, a screenshot (or even better a screencast) and of course the log (press <kbd>F12</kbd>) of the browser console.

**Comment by JS-E** [comment]
**Describe the bug**
Inability to select card description text while using the bigger card view. This stops copying and pasting from this field.

**To Reproduce**

1. Create new card with a description
2. Select this card so you can see the details in the side view
3. Click the Open in bigger view located next to the close icon in the side view
4. Try to select and copy text from the description text view.
5. Doesn't work 😢 

**Expected behavior**
I expect to be able to highlight text with my mouse and copy paste the text to another window/program

**Client details:**
- Windows 10, PC, using Firefox 86.0.1


- Server running: Docker Nextcloud 20.0.5, Deck latest version

**Comment by stefan-niedermann** [comment]
This is caused from the upstream `@nextcloud/vue-components` and has to be fixed there.

Closing in favor of https://github.com/nextcloud/nextcloud-vue/issues/1505 (Please subscribe and upvote using [GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 👍)
