### ISSUE TITLE
Feature: Add count of attachments and comments in tab headings

### ISSUE THREAD

**Issue by matthijskooijman** [nextcloud/deck#2945]
**Is your feature request related to a problem? Please describe.**
Attachments and comments are a bit hidden in other tabs. i.e. if you open a card, you end up in the "Details" tab, and it is easy to miss the fact that there are attachments or comments.

**Describe the solution you'd like**
I would like to see the number of attachments and comments in the tab, i.e. here:

![image](https://user-images.githubusercontent.com/194491/113766242-7ce28d80-971d-11eb-972b-7ec1f87d6983.png)

Show e.g. "Attachments (3)" or "Comments (2)", to provide a direct indication that there are attachments or comments to review.

**Describe alternatives you've considered**
Alternatively, some other indication of whether there are comments or not would also help (the count is not strictly useful, but it feels like a nice and intuitive way to add this indication).

**Comment by stefan-niedermann** [comment]
Spoiler: The tabs will be removed in a future version, the contents will be directly visible. Not sure whether this issue still makes sense then, but it might still be a valid feature request to display the count then.

**Comment by matthijskooijman** [comment]
> Spoiler: The tabs will be removed in a future version, the contents will be directly visible. Not sure whether this issue still makes sense then, but it might still be a valid feature request to display the count then.

Right, if that happens, than my problem is solved and I have no direct use for displaying the counts. Displaying them more directly is probably also a better way to fix this problem.

When you say "future version", do you mean this is a plan for the future? Or is this already being worked on in the git version?

**Comment by stefan-niedermann** [comment]
Not sure if actual programming has started yet (i am not a developer of this app, @juliushaertl will be able to answer this). But there are already [design proposals](https://marvelapp.com/prototype/237i8946/section/1281212) and [mockups](https://github.com/nextcloud/deck/issues/2702#issuecomment-791739112) of the future UI which are coordinated and consented by all participants as far as i know.

Since i can't see explicit proposals for the attachments, maybe @Clementine46 can post a screenshot here regarding this section, so you can tell us whether or not this solution will already solve this issue?

**Comment by juliushaertl** [comment]
There is no ETA for the new design yet and development on that has not been started, but this is the direction we'll be heading to at some point, but I agree that once we are there there would not be a need for a counter anymore.
