### ISSUE TITLE
New Field Label in CardDetails

### ISSUE THREAD

**Issue by albertomna** [nextcloud/deck#3193]
Hey Guys, really really thanks for this BEAUTIFUL application, is extremly useful! So, i have a little request for my personal use.  I am not a developer but i see the codes and sometimes i can understand something :)
I have add a field, in `CardSideBarDetails.vue` because i need another labels field (i need the same labels, not one different database).
In this new field, i must seen only the last labels added in board (example: labels.id >80).
I cannot understand the right synthax for this trouble, i think isn't hard but i cannot understand.

**Describe the solution you'd like**
Nothing new but i have copied another section wrapper under 'Tags':
```xml
<div class="section-wrapper">
    <div v-tooltip="t('deck', 'AnotherField')" class="section-label icon-tag">
        <span class="hidden-visually">{{ t('deck', 'AnotherField') }}</span>
    </div>
    <div class="section-details">
        <Multiselect v-model="assignedLabels"
            :multiple="true"
            :disabled="!isCurrentUserAssigned && !isAdmin"
            :options="labelsSorted"
            :placeholder="t('deck', 'ThisisAnotherField')"
            :taggable="true"
            label="title"
            track-by="id"
            @select="addLabelToCard"
            @remove="removeLabelFromCard">
            <template #option="scope">
                <div :style="{ backgroundColor: '#' + scope.option.color, color: textColor(scope.option.color)}" class="tag">
                    {{ scope.option.title }}
                </div>
            </template>
            <template #tag="scope">
                <div :style="{ backgroundColor: '#' + scope.option.color, color: textColor(scope.option.color)}" class="tag">
                    {{ scope.option.title }}
                </div>
            </template>
        </Multiselect>
    </div>
</div>
```

If someone can help me i am very gratefully, thanks again for this plugin!

**Comment by stefan-niedermann** [comment]
Hello @albertomna :wave: 

User defined fields are not yet supported by the Deck app (see https://github.com/nextcloud/deck/issues/1833).

I *strongly* recommend you to *not* patch the code of the Deck app this way, especially due to the fact that you are not a developer. You will need to patch your adjustments after *each and every* release of the Deck app again, manually, carefully.

Also you might see some changes on the user interface, you are missing the complete storage infrastructure for the new field - database, API and everything between. This won't work, even if you can see something in your browser, it is way more complex.

The GitHub issues are not used for providing customizing support but for bug reports and feature requests. For questions i recommend you to ask in the [Deck category of the Nextcloud help forum](https://help.nextcloud.com/c/apps/deck/83) (but to be honest there is not that much developer activity) or even better: ask for [a freelancer](https://help.nextcloud.com/c/nextcloud-freelancing/looking/49) to implement #1833 so everyone benefits :wink: :rocket:. If you are paying for a [Nextcloud enterprise subscription](https://portal.nextcloud.com/), i believe you have better chances to get support and features implemented directly by the Nextcloud core developer team (which i do not belong to by the way).
