### ISSUE TITLE
For info: big french review done

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/deck#3195]
Hi,

I've discovered the Android app for NextCloud Deck last week on F-Droid => this app is just perfect 🙏.

I have improved the french translation, see 
https://www.transifex.com/nextcloud/nextcloud/translate/#fr/android-deck/288734186

Can someone tell me when this new translation will be available for users? (when next app release is planned?).

Many thanks to all dev team members 👍,

**Comment by juliushaertl** [comment]
@stefan-niedermann can probably tell ;)

**Comment by stefan-niedermann** [comment]
Thank you very much for the praise and your contribution! :slightly_smiling_face: :rocket: 

The improved translations will be published with Deck Android `1.19.1` - we'll tag it as soon as they are [synchronized from transifex to our GitHub repository](https://github.com/stefan-niedermann/nextcloud-deck/pull/1056/files). As you know, it will take some additional time to be built and shipped by F-Droid, so i guess in 2 weeks or so the changes should arrive on your device.

PS.: The Deck Android app has [its own repository](https://github.com/stefan-niedermann/nextcloud-deck/) :wink:

**Comment by ldmpub** [comment]
@stefan-niedermann thanks for you quick answer 👍.

PS : it's hard to guess that "stefan-niedermann > nextcloud-deck" is the Deck Android app repository 😉.

**Comment by stefan-niedermann** [comment]
>  it's hard to guess that "stefan-niedermann > nextcloud-deck" is the Deck ANDROID app repository wink.

That's why we put the link in the [Play Store description](https://play.google.com/store/apps/details?id=it.niedermann.nextcloud.deck.play), the [F-Droid description](https://f-droid.org/de/packages/it.niedermann.nextcloud.deck/), the [Nextcloud App Store description](https://apps.nextcloud.com/apps/nextcloud_deck_android_app), ... basically everywhere one can get the app from :wink: 

@rakekniven The new french translations haven't been pushed to GitHub yet - i guess there is some kind of review process for new translations? Can you confirm that we just have to be a bit more patient for those changes or has anything gone wrong?

**Comment by rakekniven** [comment]
> @rakekniven The new french translations haven't been pushed to GitHub yet - i guess there is some kind of review process for new translations? Can you confirm that we just have to be a bit more patient for those changes or has anything gone wrong?

There is no review process for releasing new translations. Yes, we can review at Transifex to improve quality but as soon as a translation is saved at TX it will be synced to GitHub.

Do you see sync trouble for the android app or the server app?

**Comment by stefan-niedermann** [comment]
@rakekniven the Deck Android app, thanks for having a look!

**Comment by rakekniven** [comment]
Hmmh, there is something not working. Where to report?
