### ISSUE TITLE
Feature Request: Can all decks be seen together in "All boards" view?

### ISSUE THREAD

**Issue by flixman** [nextcloud/deck#323]
Sorry for using the "Issues" section, but I do not know how to place this request properly. Is there any way / can be added as a request to see all decks together in "All boards" view?

Thank you!
Felix

**Comment by juliushaertl** [comment]
@flixman Thanks for your feature request. Can you describe a bit more in detail, what you have in mind? 

I currently plan to add a nice startup screen, that shows an overview of the cards with nearing due dates and maybe also cards that were assigned to you, (see #12 for that) but I'm not sure if I understood your request correct.

**Comment by flixman** [comment]
@juliushaertl Hi! Sure: The idea is: in the app there is a vertical area in the left (%15 of the screen size) with contains the name with the different decks, together with "All boards" and "Archived Boards". In this startup screen. I think that makes sense for "All boards" to show all the decks together. The reason for that is: if I am using Decks to track a number of projects, would be very nice to have a global overview of all of them together.

It's just an idea, but thank you for answering! :-)

**Comment by juliushaertl** [comment]
@flixman Ok. Well just showing all stacks with cards from all of the projects might not be the best option, since those can be quite a lot. The plan with #12 is basically to provide an overview of the cards that are important right now. So it is going to be kind of a global overview, but filtered to what is important. I'm closing this in favour of #12
