### ISSUE TITLE
Bigger attachment dropzone (including empty space)

### ISSUE THREAD

**Issue by azul** [nextcloud/deck#3230]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I tried dragging files to the attachments tab but they would just open in the browser instead of getting attached.
I dragged them to the empty space below the buttons where i wanted them to appear.
I concluded that i cannot attach files with drag and drop.

Only looking at the source code i noticed that there is indeed a dragging area. Comparing the markup i noticed that it only spans the buttons and existing attachments.

**Describe the solution you'd like**
When i drag files to the empty space in the attachments tab they should become attached.

**Additional context**
Current attachment dropping zone:
![Bildschirmfoto von 2021-08-04 13-28-49](https://user-images.githubusercontent.com/102902/128173419-fd614257-a3c8-4155-8d7b-1e51ab8c44cb.png)

**Comment by dodedodo** [comment]
This should be solved by disabling the `min-height: auto`, or replacing it with `height: auto` on the `#tab-attachments` element. That would in turn mess with the padding/overflow a little, but that's not noticeable because the element is transparent anyway. The sizing thing would be solved by adding `box-sizing: border-box` to that same element.
