### ISSUE TITLE
Assign Cards from a shared board to cards within a other board

### ISSUE THREAD

**Issue by spudtnik64** [nextcloud/deck#3421]
Hi maybe i am to dumb or there is somthing wrong with my nextcloud and or deck settings. But a have issues to assign cards to another card, except, when both cards are within the first list of an board.

**Steps to reproduce the behavior:**
1. Go to 'details of a card', wich is not in the first list of an board and to 'add to a poject' 
2. Click on 'link to a card'
3. Choose any of the existing boards
4. Choose 'select a card'
5. Result: 'List is empty'

**Expected behavior**
Like if both cards are in the first list of an board, the cards list is not empty and one card can be assigned to another.

![2021-11-11 (2)](https://user-images.githubusercontent.com/94124684/141325524-d818304b-fd9f-4dd2-92ce-45963096fe6b.png)

If necessary i would provide further information about used systems and settings.
After running some tests with different constellations, it seems to me, that the main problem 'list is empty' occur, when the first list of an board is empty. When the first list has at least one card, the drop down menu of 'select a card' shows all cards of the board within the first two lists.

**Comment by juliushaertl** [comment]
As the projects feature is superseded by related resources since Nextcloud 25 there are no plans to further work on this. As long as the feature is still there anyone is of course welcome to provide fixes through pull requests but I consider this part no longer maintained.

https://github.com/nextcloud/server/blob/stable27/config/config.sample.php#L2347-L2352 
https://github.com/nextcloud/server/issues/28320
