### ISSUE TITLE
Support HEIC format

### ISSUE THREAD

**Issue by hamiltonvn** [nextcloud/deck#3435]
Nowadays, HEIC format of pictures is becoming popular. However, I found that 'deck' can not render that format properly.
Does that issue belong to nextcloud or deck or my phone (samsung Note 10)?

**Comment by louwers** [comment]
Link: https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format

It's due to lacking browser support: https://caniuse.com/heif

There's a PHP library for conversion available: https://shkspr.mobi/blog/2020/12/coping-with-heic-in-the-browser/

But the question is whether it is good to support usage of this format, as the blog post above mentions:

> HEIC is a weird, patent-encumbered format. It isn't particularly useful.

**Comment by putt1ck** [comment]
*unless you think iPhone is the raison d'etre for other tech ;)

**Comment by juliushaertl** [comment]
Image preview is handled by the viewer app https://github.com/nextcloud/viewer/issues/4 but should be available these days if the preview provider is enabled for that format.
