### ISSUE TITLE
Open links in new browser tab

### ISSUE THREAD

**Issue by HonkXL** [nextcloud/deck#3485]
At moment, links are opened in the same browser tab as nextcloud. For internal links, this is maybe ok, but if linking to external sources, this is very annyoing.

In Markdown there exists a target-setting:

`[link](url){:target="_blank"}`

But this is ignored in deck.

I think it would be a good idea to support this and/or open links in new tab as default (or configurable).

**Comment by juliushaertl** [comment]
Opening links in tabs should be the default now with deck 1.6.0 implemented with https://github.com/nextcloud/deck/pull/2791

I'm not aware of that markdown syntax being standardized (e.g. with commonmark) so we will rather not implement that in order to stick to a common baseline on the markdown syntax support.
