### ISSUE TITLE
Issues with the current board view

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#399]
There have been several issues coming up about the current board view, that all are basically caused by the scrolling behaviour. So we should consider changing that.

- Stack name is hidden when scrolling, so the context is lost: https://github.com/nextcloud/deck/issues/397
- Add card button is not visible for large stacks https://github.com/nextcloud/deck/issues/393

So a possible solution could be to make the stacks scroll individually, as proposed in https://github.com/nextcloud/deck/issues/396

Any other ideas/comments @nextcloud/deck @nextcloud/designers

**Comment by pixelipo** [comment]
#396 would not solve the fact that title and button are hidden - the only way to have that is to make both sticky and just scroll cards. 

But I am intrigued by the idea of individually-scrolling stacks - it would allow to show the bottom half of one list and a top half of another one. The problem is that this might be counter-intuitive from user perspective... @jancborchardt ?

**Comment by juliushaertl** [comment]
>  the only way to have that is to make both sticky and just scroll cards.

That was actually what I had in mind when reading #396 - basically how it works at Trello.

**Comment by jancborchardt** [comment]
Yep, making it sticky is good. And individual scrolling should be fine too. In doubt, it's not bad to do it like Trello as they have more resources for user research. :)
