### ISSUE TITLE
Assign cards to users not possible on newly created boards

### ISSUE THREAD

**Issue by himbeere** [nextcloud/deck#407]
Hello Devs.

Thanks for your work. I like the app very much.

My question. It's just a minor glitch i guess. At what point is it possible to assign a card to a user? Obviously the board must already been shared with that user? Even then i have to click "shared boards" && "the shared board" to actually be able to assign a card to a user. Before that there are no users shown to share the board with. Is that a known behaviour?

My system: NC 12.0.4, Deck 0.30, PHP-7.1

thanks and cheers
t.

**Comment by juliushaertl** [comment]
Unfortunately I cannot reproduce that. The following works for me if there are already shared users on a board:
1. Open Deck
2. Click on a board in the default list
3. Select a card
4. Click the add button in the details view
5. Add a user from the list

Besides that I think it would be a nice enhancement to also show other users and make it possible to share the board with them right from the user assignment list.

**Comment by himbeere** [comment]
Your example works for me to. Here is my workflow which does not.

1. Open Deck
2. Create Board
3. Share Board
4. Create Card
5. Share Card --> does not work. No User shown.

6. Click on Shared Boards
7. Click on the specific shared board + card --> Share with User works.

thanks and cheers
t.

**Comment by nekohayo** [comment]
I've been encountering this issue randomly, it's a bit infuriating... half of the time when I click to add a user to assign, the popup widget thingy is empty instead of offering me the users; and when it does show the users, if I type into the search box to filter down to a user, it shows no results at all (blank again). It kinda looks like a race condition.

I think I've experienced this with the "tags" as well, where sometimes clicking in the tags area of a card's sidebar doesn't let me add a tag, the click doesn't do anything.

When these kinds of things happen, I have to reload the page, or clone and reopen the tab in Firefox, or open/close the sidebar, and generally just do a bunch of voodoo to try to reset it into a working state. I'm not sure yet exactly what triggers it and what solves it.
