### ISSUE TITLE
Some actions (like creating a new card) sometimes don't trigger a visible result / board refresh

### ISSUE THREAD

**Issue by nekohayo** [nextcloud/deck#409]
With a card stack that is more than a few cards high (in my case: 16 high) the interface is fairly sluggish, and not only do I have to scroll all the way down to add a new card each time, it also seems like it doesn't create it when I click the +, type something like "Market/document feature foo at https://example" and press Enter, it seemingly doesn't create the card (but it actually does, as it shows up if I refresh the page) so I sometimes hit + again and... end up creating a duplicate.

**Comment by juliushaertl** [comment]
That is a good point. For slow internet connections this is quite a usability issue. We should either show a loading indicator or even add the card already.

**Comment by nekohayo** [comment]
You folks should benchmark Nextcloud+Deck running behind a transatlantic 100-120ms latency link... it is quite painful. This approach might reveal performance issues and race conditions. Even better if your benchmark server is a raspberry pi ;)

**Comment by juliushaertl** [comment]
@nekohayo Sadly there is still a lot of stuff to do. :wink: Help is always appreciated.

**Comment by Nebri** [comment]
@juliushaertl I'd recommend taking a look at a javascript plugin called toastr, wonderful little thing that would make for great visual ques.

**Comment by juliushaertl** [comment]
@Nebri User feedback should in general be displayed inline instead of showing a popover which misses context and distracts a lot. We have that for the success state as we then just show the new content when creating for example. We need some proper loading display mechanism for the various input fields.

As for adding a card I'd propose to instantly add the card to the DOM show a loading indicator on it until the save request has been finished.

We could add some popup for showing error messages as a temporary solution, but in general we should aim to provide feedback inline.

**Comment by juliushaertl** [comment]
We should also make sure that no duplicate create events are sent to the server. If we disable the input field on the first send and enable it again after the card has been shown, it should be fine. (as in #1140)

**Comment by juliushaertl** [comment]
This will improve a lot in the next release with the frontend rewrite. Lets close this and open new issues for individual issues rather than this general one.
