### ISSUE TITLE
{{b.title}} instead of the board name

### ISSUE THREAD

**Issue by quenenni** [nextcloud/deck#418]
Hello,

I installed on a new server (debian 9 / nginx / php7-fpm / mariadb) nextcloud 12.0.5.

When loading the deck page, there is a problem.
In the left part, under "Shared boards", instead of a board name, I see {{b.title}}

I tried the last 4 versions of deck, and in each of them, I have the same error.

There are no js errors in the console nor errors in the server log files.
I tried to create a new board, but the page reload without the new board when I validate.

All other apps I added are working well afaik and I could'nt find other reports about this.

I emptied my FF's cache to be sure. Same.

Any idea what's wrong?

Thanks

**Comment by juliushaertl** [comment]
Did you install deck from git? This looks like the js is not compiled there. Only the release archives from the app store should be used.

Otherwise please fill out the complete issue template. :wink:

**Comment by quenenni** [comment]
I downloaded from the download button -> zip file available in the code section.

The strange thing is it happened for versions of some apps I added, but every time, choosing the version before that one fixed the problem.. but they all were downloaded the same way.

So why only yours is doing that.. I'm not sure I understand all the finesse behind the different ways to get apps.

But, thanks a lot for your prompt response.
I'll see what I can do to compile the js.

**Comment by juliushaertl** [comment]
The download from GitHub is not meant to be run on production. If you download from the GitHub releases https://github.com/nextcloud/deck/releases, please make sure to download the deck.tar.gz archive, because the others (labeled Source Code also don't contain the compiled javascript). 

> So why only yours is doing that.. I'm not sure I understand all the finesse behind the different ways to get apps.
There are a couple of apps doing it this way. You should in general download apps from apps.nextcloud.com or just install them from within the apps management of your Nextcloud.

**Comment by quenenni** [comment]
Thanks for the explanation.
