### ISSUE TITLE
Unable to link Cards to Projects

### ISSUE THREAD

**Issue by rwakcjr** [nextcloud/deck#4213]
![image](https://user-images.githubusercontent.com/37149722/201865372-72effd64-c514-452d-9d8a-fb3897dd4c9f.png)

Links between cards and projects are gone, and I also can not set up new link

Docker FPM 25.0.1
PHP 8.1.12
Deck 1.8.1

**Comment by rwakcjr** [comment]
This was already implemented and working in previous versions. It seems like a bug to me

**Comment by nicovd737** [comment]
Agree that's a bug! 
We are seriously impacted by this one...

**Comment by stefan-niedermann** [comment]
Given `Projects` have been deprecated starting with Nextcloud 25 in favor of [`Related Resources`](https://github.com/nextcloud/server/issues/28320) I assume it is not a bug but expected behavior (I'm not a maintainer though, so let's wait for a reply by @juliushaertl).

**Comment by nicovd737** [comment]
Seriously ?

**Comment by Simthem** [comment]
So sad .. Really important fonctionnality for me ..

**Comment by dklueh79** [comment]
Yes, VERY sad. We used it that much....every kanban-tool has the possibility to link cards! Please reimplement.

**Comment by mortee** [comment]
I just stumbled upon this, just after discovering that I can't find my Projects after upgrading to Hub 3! 

This is absolitely crazy!

Is there a way to at least retrieve my previously hand-assembled Projects?

Has this been mentioned in the Hub 3 Release Notes? I certainly can't recall it, despite reading the announcement.

Has this been announced well in advance, very publicly, in order to give users a heads-up and time and advice to transition to some other organizational method?

**Comment by merlin-tc** [comment]
Is there any update to this? It doesn't matter if it's called projects or related resources but to remove this feature completely makes it impossible to organize bigger or interconnected projects.

**Comment by mortee** [comment]
It can be reactivated, see [here](https://help.nextcloud.com/t/lets-talk-about-projects/61326/40).

**Comment by merlin-tc** [comment]
> It can be reactivated, see [here](https://help.nextcloud.com/t/lets-talk-about-projects/61326/40).

@mortee thank you so much for that quick reply, you really helped me out. Related resources doesn't seem to be ready for prime time just yet.

**Comment by juliushaertl** [comment]
As the projects feature is superseeded by related resources since Nextcloud 25 there are no plans to further work on this. As long as the feature is still there anyone is of course welcome to provide fixes through pull requests but I consider this part no longer maintained.

https://github.com/nextcloud/server/blob/stable27/config/config.sample.php#L2347-L2352 
https://github.com/nextcloud/server/issues/28320
