### ISSUE TITLE
As Deck auto saves, everything freezes up.

### ISSUE THREAD

**Issue by buttle** [nextcloud/deck#438]
### Steps to reproduce
Edit a description of a task

### Expected behaviour
We should be able to write in the textarea

### Actual behaviour
As Deck auto saves, everything freezes up. All the different participants' icons on all the stacks reload (spinning wheel), and it is impossible to write. If you wait a little, the saving stops, and you can continue. But then the autosaves kicks in again.

**Comment by juliushaertl** [comment]
Please report the version this issue occurs.

**Comment by buttle** [comment]
Hi,

This started happening after the last upgrade to  0.3.1

**Comment by bpcurse** [comment]
Same here on Nextcloud 13.0.1, Deck 0.3.1 accessed through Firefox 59.0.1 on Manjaro Linux.
Local CPU core utilization (1 of 4) is increased to the max during the auto-save process.
The symptoms are the same as described above by buttle.

**Comment by juliushaertl** [comment]
Could you also provide some details about your browser? The best would be to fill out the complete issue template. I cannot reproduce that, even with a really slow connection (with 8s of latency for the save request)

**Comment by daniel-wtd** [comment]
Adding the template from my side, because I am affected, too.
Haven't added a ton of logs here, since there was nothing special to see.

### Steps to reproduce
1. Open Deck
2. Open a Board (mutiple tasks should exist and users should be assigned)
3. Click one existing Task
4. Choose some tags
5. Assign a/multiple users
6. Add content to the description
7. wait some seconds until auto-save
8. add more content or remove content without closing the task
9. Reloads occure from avatars when auto-save is triggered
10. lags occure even for smaller changes, due to the small freezes during avatar-reloads/auto saves

### Expected behaviour

Adding content should be fluently without interruptions and be saved after editing / adding content.

### Actual behaviour

During edits the "Autosave" is occuring multiple times.
Reloads occure from avatars when auto-save is triggered
Lags occure even for smaller changes, due to the small freezes during avatar-reloads/auto saves

### Server configuration
**Operating system**: CentOS 7.4.1708

**Web server:** Apache 2.4.6-67

**Database:** 5.5.56-MariaDB

**PHP version:** php70w-7.0.27

**Nextcloud version:** 13.0.1.1

### Client configuration
**Browser:** Firefox 59

**Operating system:** Fedora 27

**Comment by joergsch** [comment]
This issue seems to be gone if the line
> StackService.updateCard($scope.status.edit);

from `CardController.js` (line 81) gets removed.

**Comment by daniel-wtd** [comment]
@joergsch I can confirm this.

**Comment by cyborg00222** [comment]
@joergsch this only fixes it, until it saves the first time. after that, it hangs again. (and reloading everything) maybe i'm going trough the code after work. :)

**Comment by bpcurse** [comment]
Just installed Deck 0.4.0 (on Nextcloud 13.0.4) and it got better.
Not perfect, but at least it is usable again.

**Comment by juliushaertl** [comment]
@bpcurse Thanks for reporting back. Yes, there are some parts from #486 that I didn't include into #488 but I'll try to improve further for the next release.

**Comment by juliushaertl** [comment]
This is ongoing effort, therefore removing the milestone.
