### ISSUE TITLE
Cannot set due date more than one month in the future anymore

### ISSUE THREAD

**Issue by 1837456** [nextcloud/deck#4395]
Hello,

with my Nextcloud 25 (25.0.1 to 25.0.3) I cannot set the due date more than one month in the future anymore.

Because the header(?) of the calendar widget is just missing, where you can jump by month or year or can select a specific year:

![Screenshot 2023-01-19 at 09 54 45](https://user-images.githubusercontent.com/62562277/213399879-2848c42c-b34b-4c09-b834-0127a1e13011.png)

Should be like this:

![Screenshot 2023-01-19 at 09 55 52](https://user-images.githubusercontent.com/62562277/213400667-84fc6f5d-d307-4dda-bfdc-49fad4c1fc68.png)

**Comment by 1837456** [comment]
Ok, I narrowed down this issue:

Above issue exists on existing cards only.

It works as expected on newly created cards:

![Screenshot 2023-01-19 at 11 22 02](https://user-images.githubusercontent.com/62562277/213418418-cf0aa3cd-35d7-4aad-8881-4e73aef98d76.png)

**Comment by martinclauss** [comment]
Same problem here with Nextcloud 25.0.3

**Comment by nwinkelstraeter** [comment]
Also happens here with Nextcloud 25.0.3
It seems to be just a display problem where the top controls are not visible.
If you open the description text field the card enlarges enough so that the calendar opens to the bottom instead of to the top. Then the controlls are visible again.
![controls_visible](https://user-images.githubusercontent.com/81554102/214248444-28e5b3d9-3f8f-4cfe-8089-47aeae5b0b73.png)
![controls_not_visible](https://user-images.githubusercontent.com/81554102/214248448-acba53f2-d106-4023-8933-18606c6b6a6f.png)

**Comment by martinclauss** [comment]
Yes, I can confirm this. Setting the height to e.g. 1000px "solves" the problem and the calendar opens up in the bottom direction:

```html
<div data-v-295df2d8="" id="modal-description-tgvej" class="modal-container" style="
    height: 1000px;
">...</div>
```

**Comment by 1837456** [comment]
Yes, this actually works.

**Comment by reox** [comment]
See also #4296 - same issue: the modal container is simply too small.
