### ISSUE TITLE
Better calendar integration and hwo to handle finished tasks

### ISSUE THREAD

**Issue by schiessle** [nextcloud/deck#4835]
I started to use Deck more often to manage my tasks and run into some issues with the calendar integration.

The calendar integration. It is really nice to expose my Deck boards as calendars. But at the moment this tasks show than up on various places: 

* Nextcloud Task app
* Nextcloud Calendar
* Desktop/mobile clients which sync the calendar

But all have in common that I can not complete / tick-off a task. Which means that I get notified forever until I go to deck and archive  or delete it. It would be nice if we could tick-off on the various clients the tasks like regular caldav tasks and translate it server side to a useful action.

... This lead me to the second part:

As mentioned before, the only way to complete a task is to archive it or delete it. It would be nice to have a logic like, everything moved to a "Done" column is considered as done. This way we could move ticked-off tasks to the done column and they would no longer show up in the external clients as open tasks and also not in "upcoming cards" of Deck.

Another option would be to archive tasks ticked-off with a client and maybe give them a additional label like "completed" so that if the user looks later at the archived card they know why the card was archived.

Or a third option?

**Comment by stefan-niedermann** [comment]
And again: This all is caused by a missing `done` state and has been discussed so many times: https://github.com/nextcloud/deck/issues/534 (There even exists a [PR](https://github.com/nextcloud/deck/pull/4137)).

Additionally: For your use case there are further issues which need to be fixed, like https://github.com/nextcloud/deck/issues/2399

Howevery, it is everything here. It has been documented and discussed in the growing number of issues. [*Many* times](https://github.com/nextcloud/deck/assets/4741199/ff95ff24-539a-48a8-9fef-b34a97e1b8a1)... Sorry, I don't want to sound harsh, but it is quite hard to keep the issue tracker clean, so please, as we all tell the community and users: Search for existing issues before opening duplicate ones :wink:

**Comment by schiessle** [comment]
@stefan-niedermann I just didn't found the other tickets :see_no_evil: Let's close this one than and follow up on the existing one.
