### ISSUE TITLE
color_picker.svg is "invisible" on white background

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#501]
**Describe the bug**
When a new tag is white, the icon of the colorpicker is invisibile (white on white background)

**To Reproduce**
1.  Create a new tag (default colour is white)
2. See error: The icon of the colorpicker is not visibile (white on white)

![deck_0 4 0 beta](https://user-images.githubusercontent.com/34692335/41678961-e7aa411a-74cc-11e8-9dff-8b16fb5b6cc5.png)

**Expected behavior**
The icon of the colorpicker is visibile, ex. grey background of color_picker.svg

** Tested on :** 
 - deck  0.4.0-beta1
 - Nextcloud 13.0.4
 - Ubuntu 18.04
 - Firefox 60.0.2

**Where did you install Nextcloud from:**
github releases

**Comment by juliushaertl** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by juliushaertl** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/nextcloud/deck/issues/225 (Deck icon is white in apps management).

**Comment by juliushaertl** [comment]
Fixed by #511
