### ISSUE TITLE
Better Dark Mode Style

### ISSUE THREAD

**Issue by jacksbox** [nextcloud/deck#5034]
The list and card style in dark mode could be optimised. (It seems to use the same colors as the light theme):
* It is hard to destinquish between cards
* The Due-Date pops really hard and distracts from everything else, but the grey text on it is not readable very good

<img width="329" alt="Screenshot 2023-08-18 at 10 50 43" src="https://github.com/nextcloud/deck/assets/1983877/5c981afa-29c1-4bcd-acb6-f29c231cf3e6">

**Comment by juliushaertl** [comment]
We used to have a 2px border instead of the box shadow on dark mode but that seems broken.

@nextcloud/designers How about generally moving to a border for the cards instead of the box shadow? This seems to fix the general Nextcloud design more these days.

| Before | After (primary indicates currently selected/open) |
|---|---|
| ![Screenshot 2023-08-22 at 08 36 38](https://github.com/nextcloud/deck/assets/3404133/3abd0d18-c64e-4e8b-8ae8-3fd9f00ab247) | ![Screenshot 2023-08-22 at 08 36 01](https://github.com/nextcloud/deck/assets/3404133/33d244fe-95de-4dc2-97a8-84bc664f5c3d) |
| ![Screenshot 2023-08-22 at 08 36 47](https://github.com/nextcloud/deck/assets/3404133/130e473c-1086-4d96-a708-8c8ce94d9bcd) | ![Screenshot 2023-08-22 at 08 36 15](https://github.com/nextcloud/deck/assets/3404133/b2667722-e982-497c-b81a-d2eb0e5681d6) |

**Comment by juliushaertl** [comment]
For the due date I'll check if we have better color variables these days that work with both dark/light mode
