### ISSUE TITLE
Unable to modify profile picture 

### ISSUE THREAD

**Issue by valentinjacot** [nextcloud/deck#5418]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Hi
I'm unable to change the profile picture on https://intranet.hebamme.ch/cloud/index.php/apps/schweizerhebammenapp/#!
I get a error 500 when sending the request: POST https://intranet.hebamme.ch/cloud/index.php/apps/schweizerhebammenapp/midwife_data_upload_profile_picture/

I tried several browser and machines, the issue is always the same. My current picture is broken, so on the public space it shows nothing

**To Reproduce**
1. Go to https://intranet.hebamme.ch/cloud/index.php
2. Click on Upload Picutre
3. Select picture 
4. Click Save
5. Wait 5 Minutes and a 500 error appears in the dev tool

**Expected behavior**
I want the new picture to be uploaded. I is a JPEG of less than 1 MB

**Screenshots**
<img width="1440" alt="Bildschirmfoto 2024-01-01 um 11 38 19" src="https://github.com/nextcloud/deck/assets/14948405/d9994c07-e48d-40f1-9466-64632ea1b587">

**Client details:**
 - OS: IOS
 - Browser chrome, safari, firefox
 - Device: desktop

I'm looking forward to your answer, as this is used for a professional website the broken picture looks pretty bad.
Best regards
VJD

**Comment by stefan-niedermann** [comment]
Nothing seems to fit on this issue:

1. You wrote, your client is `iOS` on a `Desktop`, `iOS` is a smartphone operating system though.
2. Your issue is about uploading an avatar, a feature that is not included in the Nextcloud Deck App
3. The paths of your dev tool screenshots hint about a (for me) unknown third party app called `schweizerhebammenapp` instead of `deck` (this is the issue tracker for the Nextcloud Deck app though)

Are you sure you are in the correct place? If you are an administrator, you should double check the correct issue tracker for your problem. If you are an user, you should ask the administrator / IT ressort of your intranet.

**Comment by valentinjacot** [comment]
Thanks, I'll do that.
BR
