### ISSUE TITLE
Configuration setting for width of stacks

### ISSUE THREAD

**Issue by Brianetta** [nextcloud/deck#553]
I use a relatively small screen, on which I can see two and a half stacks in my board. I'd be grateful if the width of the stacks could be manually adjusted to suit the user. I'm not suggesting automatic scaling (I read #82) but just a simple input where I can manually scale all of my stacks horizontally.

Zooming doesn't help; by the time I see a reasonable number of stacks, the text is too small. Additionally, I have to re-zoom whenever I use other parts of Nextcloud.

**Comment by juliushaertl** [comment]
We should not introduce a setting for UI preferences here. This will cause various problems, since the card view is not only about a text that can be shrinked but also has indicator icons, that need some space.

We already have the option to hide the left sidebar, so that should give you a bit more space. In general space is always limited somehow and it really depends on the number of stacks/cards you have. I guess we cannot find a solution that works for all screen sizes as well as any number of stacks.

**Comment by Brianetta** [comment]
Thanks for you time. I'll find some other software.
