### ISSUE TITLE
new Cards lost Notes and Links

### ISSUE THREAD

**Issue by rsedlmeier** [nextcloud/deck#5652]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
New Notes and Links are lost at a new Card
Up to NC 27 this one never happend

**To Reproduce**
1. Create a new Card
2. Fill some contend and add a note and a link
3. close the card
4. wait a few seconds and open the card and the notes and links are gone

**Expected behavior**

**Screenshots**

**Client details:**
 - OS: ubuntu 22.04
 - Browser all
 - Version
 - Device: desktop 

<details>
<summary>Server details</summary>

**Operating system**: unbuntu 22.04

**Web server:** apache2

**Database:** mariadb

**PHP version:** 8.2

**Nextcloud version:** (see Nextcloud admin page) NC 28.0.2

**Where did you install Nextcloud from:** NC update

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by pundip** [comment]
I have the same issue where I cannot save the description on a card. The issue is intermittent where I cannot save it say 95% of the time but occasionally it will save the description:

NC 28.0.3
Deck version 1.12.2 

PHP Version: 8.1.2
Memory limit: 2 GB
Max execution time: 3600
Upload max size: 2 GB
OPcache Revalidate Frequency: 1
Database Type: mysql
Version: 8.0.36
Size: 1.2 GB
 
Operating System: Linux 5.15.30-2-pve x86_64
CPU: Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz (10 cores)
Memory: 15.63 GB
Operating System: Linux 5.15.30-2-pve x86_64
CPU: Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz (10 cores)
Memory: 15.63 GB
Uptime: 7 hours, 52 minutes, 20 seconds

**Comment by rsedlmeier** [comment]
upgraded to 29.0.4 and it seams to work again.
Comments, Links and gifs are stored.
