### ISSUE TITLE
file browser keeps empty with only grey lines

### ISSUE THREAD

**Issue by leclou69** [nextcloud/deck#5822]
**bug description**
trying to add files from within nextcloud to deck card, but list of files /directories only shows grey lines

**To Reproduce**
1. Go to 'Deck'
2. Click on existing deck card to see the details
3. Click on 'Attachments'
4. Click on 'Share from files'

**Expected behavior**
A list of files / directories should be presented, but instead there are only grey lines

**Screenshots**
![grafik](https://github.com/nextcloud/deck/assets/13885384/0cf218de-3322-4d9b-8ff3-e4efaef0b449)

**Client details:**
 - OS: docker latest
 - Browser: chrome, Firefox
 - Version Nextcloud: 29.0.0 deck: 1.13.0
 - Device: desktop

<details>
<summary>Logs</summary>

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
main.js:56 TypeError: Cannot read properties of undefined (reading 'authType')
    at H (request.js:71:17)
    at index.mjs:405:117
    at index.js:2:55017
    at R.execute (index.js:2:54338)
    at R.patchInline (index.js:2:55925)
    at X (index.js:2:59820)
    at index.js:2:59436
    at index.js:2:58252
    at index.js:2:86641
    at n (index.js:2:86363)
l.default.config.errorHandler @ main.js:56
mn @ vue.runtime.esm.js:3047
un @ vue.runtime.esm.js:3024
(anonymous) @ vue.runtime.esm.js:3035
Promise.catch (async)
cn @ vue.runtime.esm.js:3035
qn @ vue.runtime.esm.js:4048
insert @ vue.runtime.esm.js:4443
E @ vue.runtime.esm.js:6966
xi.nodeOps @ vue.runtime.esm.js:7180
e._update @ vue.runtime.esm.js:3785
r @ vue.runtime.esm.js:3891
e.get @ vue.runtime.esm.js:3462
e.run @ vue.runtime.esm.js:3538
rr @ vue.runtime.esm.js:4141
(anonymous) @ vue.runtime.esm.js:3159
An @ vue.runtime.esm.js:3081
Promise.then (async)
fn @ vue.runtime.esm.js:3106
Tn @ vue.runtime.esm.js:3171
ar @ vue.runtime.esm.js:4227
e.update @ vue.runtime.esm.js:3529
e.$forceUpdate @ vue.runtime.esm.js:3810
c @ vue.runtime.esm.js:2777
(anonymous) @ vue.runtime.esm.js:2797
(anonymous) @ vue.runtime.esm.js:312
Promise.then (async)
m @ vue.runtime.esm.js:2821
mr @ vue.runtime.esm.js:4494
(anonymous) @ vue.runtime.esm.js:2943
sn @ vue.runtime.esm.js:2882
e.$createElement @ vue.runtime.esm.js:2656
render @ legacy.mjs:36
e._render @ vue.runtime.esm.js:2700
r @ vue.runtime.esm.js:3891
e.get @ vue.runtime.esm.js:3462
e @ vue.runtime.esm.js:3452
e @ vue.runtime.esm.js:3908
jr.$mount @ vue.runtime.esm.js:8797
e._init @ vue.runtime.esm.js:5724
jr @ vue.runtime.esm.js:5785
c @ legacy.mjs:33
r @ legacy.mjs:100
(anonymous) @ index-CRno7JSe.mjs:17
pick @ index-CRno7JSe.mjs:10
await in pick (async)
shareFromFiles @ AttachmentList.vue:228
click @ AttachmentList.vue:1
cn @ vue.runtime.esm.js:3033
n @ vue.runtime.esm.js:1832
cn @ vue.runtime.esm.js:3033
e.$emit @ vue.runtime.esm.js:3732
click @ NcButton.mjs:199
cn @ vue.runtime.esm.js:3033
n @ vue.runtime.esm.js:1832
i._wrapper @ vue.runtime.esm.js:7500
Show 49 more frames
Show less

</details>

**Comment by CompassResearch** [comment]
Same problem. We have analyzed logs and error msgs and tried various fixes, but didn't help. 

Here's a Chat GPT analysis based on our error messages:
----
The error messages you've provided from your Nextcloud 29.0.0 instance, specifically concerning the DECK app, highlight a PHP coding issue in the DECK app's ConfigService.php. Here’s a breakdown of the key components of the error and what they might indicate about the underlying problem:

Error Details
Both error messages point to the same issue within a method in the ConfigService.php file at line 234. The error message:

"Optional parameter $userId declared before required parameter $path is implicitly treated as a required parameter"
This error is typical of a function or method declaration in PHP where an optional parameter (one with a default value) is placed before a required parameter (one without a default value) in the function's signature. This is problematic in PHP because it forces all parameters defined after an optional parameter to also be treated as optional, which can lead to unexpected behavior or errors.

Context of the Error
The errors are triggered during GET requests to the Nextcloud server:
URL /ocs/v2.php/apps/user_status/api/v1/user_status?format=json
URL /ocs/v2.php/apps/notifications/api/v2/notifications?format=json

These URLs suggest that the requests are related to fetching user status and notifications, respectively.

Analyzing the Impact
Although the URLs involved in the errors pertain to user statuses and notifications, the error originates from the deck app's codebase, suggesting that the DECK app might be extending or interacting with these areas of Nextcloud.
This might indicate that there's a broader integration issue within the DECK app that could be affecting its ability to properly manage or access file structures as you’ve been experiencing.

Steps to Resolve
Review and Modify Code: The immediate resolution would be to check the ConfigService.php file around line 234 and adjust the parameter order. The optional parameter $userId should be placed after all required parameters, or it should be made required by removing its default value if that contextually makes sense.

Update and Test: After making code changes, thoroughly test the DECK app in a development environment to ensure that the change does not negatively affect other functionalities.

Check for Updates: Verify if there's an update available for the DECK app that addresses this issue. Sometimes, such problems are quickly fixed once identified, and an update might already be available.

Report the Issue: If this issue persists and no updates seem to address it, consider reporting it to the Nextcloud DECK GitHub repository or support forum. Providing them with detailed error logs, server environment details, and steps to reproduce the issue can help in obtaining a more permanent fix.

Fallback Plan: If the issue is critical and a fix is not readily available, consider rolling back to an earlier version of the DECK app or Nextcloud where this issue was not present, if such a rollback would not cause other issues.

-------------

We tried that, but it didn't help either.

**Comment by Keeper-of-the-Keys** [comment]
This is probably related to the new File Picker dialog
https://github.com/nextcloud/server/pull/39792

**Comment by araspitzu** [comment]
I'm also affected by this issue, when trying to select an attachment for a card the file browser is not working and shows up but remains in a disabled state. The file browser works correctly from other apps.

Client details:

    OS: docker latest
    Browser: Firefox
    Version Nextcloud: 29.0.0.19
    Deck: 1.13.0
    Device: desktop

**Comment by luistiktok** [comment]
Same happens when trying to achieve the same but in the calendar app

**Comment by leclou69** [comment]
> Same happens when trying to achieve the same but in the calendar app

Yeah, indeed. Also still persists in the calendar app after upgrading it today to latest 4.7.4.
So perhaps sth the main nc branch should have an eye on.
In Mail i.e. it works as it should.

**Comment by leclou69** [comment]
> Same happens when trying to achieve the same but in the calendar app

In calendar it seems to be fixed with te actual version 4.7.6

**Comment by leowenlu** [comment]
got the exactly same error, any one has solution for this?
dock: 1.13
nextCloud: 29.0.1

**Comment by Spheren** [comment]
Same here.

dock: 1.13
NC: 29.0.3

**Comment by leclou69** [comment]
Today Deck 1.13.1 was released.
The problem is solved
