### ISSUE TITLE
overlay shared-icon like in app files

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#668]
**Is your feature request related to a problem? Please describe.**
just increase consistency to app files

**Describe the solution you'd like**
For shared boards overlay the shared-icon in the bullet just like in the app files for shared folders

**Describe alternatives you've considered**
Change nothing to keep the UI clear

**Additional context**
app files:
![screenshot_2018-10-31 files - nextcloud_klein](https://user-images.githubusercontent.com/34692335/47848658-5511d180-ddcf-11e8-8513-ebefcd162501.png)

suggestion for deck:
![screenshot_2018-10-31 deck - nextcloud_klein](https://user-images.githubusercontent.com/34692335/47848879-0a448980-ddd0-11e8-8ec0-7130056f3700.png)

**Comment by juliushaertl** [comment]
Thanks for your suggestiong @cloud2018. While I like the indicator in the right board list, the small icon in the sidebar is definitely to small to be recognized. I think we should instead display it the same way other apps like calendar/contacts are doing it:

![image](https://user-images.githubusercontent.com/3404133/47849466-00bc2100-ddd2-11e8-9358-9b24a69570c6.png)

For the main list, we probably don't need the sharing indicator at all, since we have a list of user avatars, the board is shared with there.

![image](https://user-images.githubusercontent.com/3404133/47849560-60b2c780-ddd2-11e8-9ced-6e7c576b239b.png)

cc @nextcloud/deck

**Comment by juliushaertl** [comment]
cc @weeman1337 Something we can probably quickly integrate into the vue branch.

**Comment by juliushaertl** [comment]
Closing as this was implemented in the vue branch and is now merged to master
