### ISSUE TITLE
Integrating with Wekan

### ISSUE THREAD

**Issue by iAdanos** [nextcloud/deck#76]
Adding Kanban with tasks integrated in Nextcloud is great!

But there are already more functional open-source products like [Wekan](https://github.com/wekan/wekan)
Why not to intergate with them instead of re-developping everything?

**Comment by juliushaertl** [comment]
Wekan is build with node.JS so it requires a totally different software stack. As nextcloud is easy to run because it basically just requires a lamp stack, I don't like solutions that won't work out of the box with that.

Besides that I started this initially as a learning project to get familiar with angular js. :wink:
