### ISSUE TITLE
Redesign card view

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#938]
Design session for the Android client with @jancborchardt brought up a detail issue:

Instead of displaying an icon when a description is present we will show on android the first line (truncated description).

Maybe this should be the same behavior on the server app?

![deck](https://user-images.githubusercontent.com/4741199/54373607-dd598a80-467d-11e9-94db-60e11265b2ef.png)

**Comment by juliushaertl** [comment]
Makes sense to me :+1:

**Comment by stefan-niedermann** [comment]
Just for docu: this is how a card looks like on the Android app currently:

![grafik](https://user-images.githubusercontent.com/4741199/54383793-28ca6380-4693-11e9-8e74-1145fb862154.png)

**Comment by juliushaertl** [comment]
@jancborchardt I'm not sure if we actually should condense the labels, this makes them look to similar to avatars and also doesn't provide enought information what the label is about. The text should be fully visible I think, since otherwise users will always need to remember which labels they have on their boards and the first letter isn't a clear indicator. Just think of labels as we use them in the server repo, where we prefix labels for grouping. ("feature: files" and "feature: settings" have the same color and same beginning but they still should be distinguishable in the UI)

**Comment by juliushaertl** [comment]
@stefan-niedermann Appart from the comment above the new layout looks much cleaner. :+1: Avatars are displayed in the bottom right (just to have that referenced here as well)

**Comment by fti7** [comment]
Why not moving the labels to the top? like in the other kanban tools?
Trello usually condenses it by default.
In the most Boards there are just a handful Labels; No need for a Text
But it also allow to uncondense it via an Click.

![Screenshot from 2019-04-04 14-13-50](https://user-images.githubusercontent.com/7014664/55554929-5039ac80-56e4-11e9-9ab4-d53777bd5fcd.png)
![Screenshot from 2019-04-04 14-14-06](https://user-images.githubusercontent.com/7014664/55554930-53349d00-56e4-11e9-916d-cde5cf48221d.png)

Personally i would also like to see such an layout in the Web App. The current layout needs too much space if you have many cards :-)

**Comment by jancborchardt** [comment]
@fti7 the first screenshot looks really good, but the issue here is that then the label only relies on color as a distinction and would thus be difficult to distinguish for people with color vision difficulties.

> But it also allow to uncondense it via an Click.

Click/tap opens the details at the moment.




------------------

@stefan-niedermann I don’t fully remember what was the last state but I remember we had a nice solution in the Android app on the last day of the Contributor Week after the input of @jenniferpiperek? As far as I remember we and @juliushaertl were quite happy with that. Could you post a screenshot? :)

**Comment by juliushaertl** [comment]
@jancborchardt This is the android app layout https://github.com/nextcloud/deck/issues/938#issuecomment-473012650 

![https://user-images.githubusercontent.com/4741199/54383793-28ca6380-4693-11e9-8e74-1145fb862154.png](https://user-images.githubusercontent.com/4741199/54383793-28ca6380-4693-11e9-8e74-1145fb862154.png)

This is the current look in the web UI:
![image](https://user-images.githubusercontent.com/3404133/56369054-e5ff2c80-61f8-11e9-8df2-58ecc0f7e70d.png)


As written above I'm not to happy with just showing the first letter of the label, as this might lead to confusion if users have multiple labels of the same color. 

Since we have a compact view in the web UI, how about just showing color labels on that compact mode and expand the information if the regular mode is used similar to this:
![https://user-images.githubusercontent.com/7014664/55554930-53349d00-56e4-11e9-916d-cde5cf48221d.png](https://user-images.githubusercontent.com/7014664/55554930-53349d00-56e4-11e9-916d-cde5cf48221d.png)

**Comment by jancborchardt** [comment]
> This is the android app layout [#938 (comment)](https://github.com/nextcloud/deck/issues/938#issuecomment-473012650)

Yep, I got that, but since it was from March 14 I thought on the last day of the hackweek we did some additional work on it? I had remembered @stefan-niedermann worked on it some more with some layout improvements. Maybe I misremember.

**Comment by jakobroehrl** [comment]
@jancborchardt 
What do you think about the last state? (Server App)
![grafik](https://user-images.githubusercontent.com/24530680/63920107-5be59100-ca40-11e9-9749-52f10ae01130.png)

Thanks!

**Comment by jancborchardt** [comment]
@jakobroehrl good stuff! Only 2 things:
- I’d say tags should never wrap lines but be forced into one line. If there’s more tags, they should just ellipsize. Maybe with flexbox so each of the tags ellipsizes a bit?
- The people avatars/circles should overlap a bit like we do in the Text app:
  ![Text app high dpi avatars blurry](https://user-images.githubusercontent.com/925062/61301260-deddbf80-a7e3-11e9-9271-4293cf5628d9.png)

**Comment by jakobroehrl** [comment]
@jancborchardt Thanks, I will try to implement it. 
Maybe you could review the complete VUE Implementation when we are ready to release?

**Comment by juliushaertl** [comment]
Closing as this was implemented in the vue branch and is now merged to master.

**Comment by alexanderdd** [comment]
discussion continues here https://github.com/stefan-niedermann/nextcloud-deck/issues/298
