### ISSUE TITLE
Feature Request : notifications of card due dates

### ISSUE THREAD

**Issue by sh2515** [nextcloud/deck#970]
Would you be able to add a feature to your roadmap please.

I have cards on several boards with dates and I am not on the internet all the time to check for notifications on the nextcloud webpage, so I would like to get notifications on my mobile phone.

When I set a card with a due date, I would like a reminder to popup on my phone as well, maybe even set when I want a reminder.

Alternatively tasks app is good for reminders but there is no structure to it like deck, is there the ability to move the notification function from this to deck. Alternatively would it be possible to add cards with dates to a calendar and then subscribe to that calendar, where deck would automatically set a notification.

**Comment by juliushaertl** [comment]
Once a card reaches its duedate a notification a notification will be sent to all users of the board, for a possible enhancement to only sent it to assigned users see #566. Note there might be a small delay in the notification, since we only check it on the run of the cron job.

> Alternatively would it be possible to add cards with dates to a calendar and then subscribe to that calendar, where deck would automatically set a notification.

This is handled in #15
